### ISSUE TITLE
能否加入多列数据的pick呢？

### ISSUE THREAD

**Issue by sunnylqm** [beefe/react-native-picker#1]
谢谢！

**Comment by xwenliang** [comment]
后面会添加此支持，如果需求紧急的话，可以由[react-native-picker-android](https://github.com/beefe/react-native-picker-android)自行二次封装一个

**Comment by xwenliang** [comment]
@sunnylqm 
已支持多列数据的picker: https://github.com/beefe/react-native-picker/commit/34d81a577e5b5756959c568f54dfc06b8c704524

**Comment by sunnylqm** [comment]
bravo!
