### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by mvpdream** [beefe/react-native-picker#10]
var pickerData = {
       a: {
           a1: [1,2,3,4],
           a2: [5,6,7,8],
           a3: [9,10,11,12]
       },
       b: {
           b1: [1,2,3,4],
           b2: [5,6,7,8],
           b3: [9,10,12,12]
       }

   };
var selectedValue = ['a', 'a1', 1];
我用的这组数据，我选择a，a2.应该第三列是5,6,7,8 但是还是1,2,3,4

**Comment by xwenliang** [comment]
你在onPickerDone里面需要更新selectedValue
