### ISSUE TITLE
4.0.14版，3级联动的时候，第一行数据中，无论怎么选择第二级，相应的第三级都不会改变

### ISSUE THREAD

**Issue by codywch** [beefe/react-native-picker#109]
难道只有我一个人有这个问题吗？

**Comment by codywch** [comment]
IOS中~~Android应该是好的。。

**Comment by xwenliang** [comment]
iOS确实有这个问题....正在修复

**Comment by xwenliang** [comment]
更新到`4.0.15`就好了

**Comment by codywch** [comment]
66666

**Comment by codywch** [comment]
咦~~4.0.15版是好的吗？我这貌似还是没变诶。。

**Comment by shexiaoheng** [comment]
@codywch  把旧版本全部移除，重新安装和引用新版

**Comment by shexiaoheng** [comment]
应该是。。。

**Comment by codywch** [comment]
![image](https://cloud.githubusercontent.com/assets/4686764/21667442/1b82a8ce-d334-11e6-8e12-b39ad609ed79.png)
![image](https://cloud.githubusercontent.com/assets/4686764/21667529/c7a80dc4-d334-11e6-8898-1641350e389d.png)
![image](https://cloud.githubusercontent.com/assets/4686764/21667536/de37f360-d334-11e6-80b6-abde0b4e9beb.png)
我用新项目装的。。。还是不会变，@shexiaoheng 能帮我看看吗

**Comment by xwenliang** [comment]
@codywch  非常抱歉，我只在本地代码测试了，结果这里的代码改错了，现在应该是好的了 `4.0.16`

**Comment by codywch** [comment]
高效！恩现在好了。辛苦了。谢谢！

**Comment by yongqianvip** [comment]
刚准备 pull request 发现 bug 被修复了
点个赞
<img width="1020" alt="bug" src="https://cloud.githubusercontent.com/assets/5046614/21719134/010a581a-d457-11e6-85cb-24dcaad80020.png">
