### ISSUE TITLE
android原生 跳转react,Picker.show() err.

### ISSUE THREAD

**Issue by wubangshun** [beefe/react-native-picker#112]
Cannot read property 'showImagePicker' of undefined

**Comment by JusticeLai** [comment]
我的安卓旧项目,有一个入口跳转进入ReactNative,然后有个地方调用这个组件...报错说找不到这个组件....之前写的例子是纯ReactNative就不会报错.
![image](https://cloud.githubusercontent.com/assets/13083749/21801989/fa1cea4e-d75e-11e6-9f3b-631039854f9a.png)

**Comment by shexiaoheng** [comment]
#108
