### ISSUE TITLE
How to change font family?

### ISSUE THREAD

**Issue by waterdoo** [beefe/react-native-picker#116]
Is there a way to change the font family to Roboto or sans-serif? I've tried searching for all instances of "fontFamily" in your package but after changing it and rebuilding, it goes back to normal.

**Comment by waterdoo** [comment]
Just to let others know, I was able to change the font family to Roboto (Sans serif) by editing both occurrences of "Typeface.MONOSPACE" in the Loopview.java file to "Typeface.SANS_SERIF".

It'd be nice if this was a feature, like adjusting the font size, but overall no complaints here. Thanks for making a great package!

**Comment by arcollector** [comment]
HI, I just changed Typeface.SANS_SERIF, but it didn't work, how do you make it worked?

**Comment by waterdoo** [comment]
Did you rebuild using react-native run-android?
