### ISSUE TITLE
DatePicker的日期问题

### ISSUE THREAD

**Issue by LzxHahaha** [beefe/react-native-picker#12]
改变月份后，日期不会变化

**Comment by LzxHahaha** [comment]
试了一下，j 的值一直为1……这是什么情况

**Comment by xwenliang** [comment]
我刚刚看了下，应该是正常的，你的react-native-picker是最新的0.3.4吗？

**Comment by LzxHahaha** [comment]
是0.3.4的，我把代码重新拷一遍试试。。

**Comment by xwenliang** [comment]
好像iOS确实是有问题的，我debug下

**Comment by xwenliang** [comment]
@LzxHahaha 
非常感谢发现了这个bug，已经修复 https://github.com/beefe/react-native-picker/commit/1f20b69f2ae3cc660c52453bef3bfef837822838
