### ISSUE TITLE
undefined is not an object(evaluating 'Picker._init')

### ISSUE THREAD

**Issue by chaoyangrunning** [beefe/react-native-picker#125]
这怎么回事？

**Comment by 495640129** [comment]
我也是这个问题

**Comment by xwenliang** [comment]
`npm install`后确保执行了`react-native link`，试试[example](https://github.com/beefe/react-native-picker/tree/master/example)也会这样吗

**Comment by chaoyangrunning** [comment]
已解决！  原因是我将xcode中的依赖删除了。解决方案.重新删除RCTBEEPickerManager项目 再react native link后 运行解决。


发自网易邮箱大师
在2017年02月24日 11:11，zooble 写道：

npm install后确保执行了react-native link，试试example也会这样吗

**Comment by 495640129** [comment]
以解决，谢谢！
执行react-native link，然后react-native run-android重新打包，我之前没有重新打包，只是执行了npm start。



495640129@qq.com
 
From: zooble
Date: 2017-02-24 11:27
To: beefe/react-native-picker
CC: 495640129; Comment
Subject: Re: [beefe/react-native-picker] undefined is not an object(evaluating 'Picker._init') (#125)
Closed #125.
