### ISSUE TITLE
Invariant violation (React Native 0.17)

### ISSUE THREAD

**Issue by Sexycrets** [beefe/react-native-picker#13]
Your picker looks great and customizable on your pictures. I installed it with npm and copy pasted your /demo/date-picker.js example in datepicker.js. Then I included it in my main project and called it in the view: 

```
var DatePicker = require('./datepicker');
[...]
<View style={styles.formAnswersContainer}>
     <DatePicker/>            
</View>
```

The error I get on the iOS simulator is 
```
Invariant Violation: Element Type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of 'exports'.

What am I doing wrongly?
```

**Comment by xwenliang** [comment]
try `import DatePicker from './datepicker'` or `var DatePicker = require('./datepicker').default`

**Comment by onthedesk** [comment]
Cool!

**Comment by Sexycrets** [comment]
Works with adding ```.default```, thank you!
