### ISSUE TITLE
rnpm-link安卓无效，ios有效

### ISSUE THREAD

**Issue by RealAmissio** [beefe/react-native-picker#131]
import com.beefe.picker.PickerViewPackage;
            new PickerViewPackage()
这两句安卓一执行rnpm link就会把这两句去掉，得自己重新加，这是为什么。。。

**Comment by xwenliang** [comment]
rnpm已经是很久之前的版本的，因为react-native在不停的更新导致它需要同步更新，作者嫌累就把它集成到react-native项目中了，所以安装命令变成了`react-native link`
