### ISSUE TITLE
【iOS】选择省／市的同时获取到省／市对应的code用于数据传递

### ISSUE THREAD

**Issue by huangxiaohao** [beefe/react-native-picker#136]
您好，这是一款很棒的picker。
我在使用的时候，需要在选择完省／市的同时获取到相对应地code；例如选择`["河北省", "石家庄市"] `的同时获取到河北省对应的  `areaCode: "3"` 和 石家庄市对应的`areaCode: "1003"` 用于后续数据传递。
请问 我该如何去操作呢？谢谢。

**Comment by huangxiaohao** [comment]
下图为我将获取到的数据拼接为组件所需的标准格式：
![image](https://cloud.githubusercontent.com/assets/13390763/24576715/b143c8b8-16f3-11e7-9350-ad834a93cf1a.png)

下图为我获取的数据格式：
`
{
resData: {
province: [
{
areaCode: "1",
name: "北京市",
nid: "0",
city: [
{
areaCode: "1001",
name: "北京市",
nid: "1"
}
]
},
{
areaCode: "2",
name: "天津市",
nid: "0",
city: [
{
areaCode: "1002",
name: "天津市",
nid: "2"
}
]
},
{
areaCode: "3",
name: "河北省",
nid: "0",
city: [
{
areaCode: "1003",
name: "石家庄市",
nid: "3"
},
{
areaCode: "1004",
name: "唐山市",
nid: "3"
},
...
...
...
`

**Comment by xwenliang** [comment]
这个目前确实没有很好的支持，可以使用类似[lodash](https://lodash.com/docs/4.17.4#find)的工具来查找到原始数据，然后一层层的取出

**Comment by xwenliang** [comment]
ES2015已经原生支持了，写法类似于：
```javascript
let province = [
    {areaCode: "1", name: "北京市"},
    {areaCode: "2", name: "上海市"},
    {areaCode: "3", name: "广州市"}
];

function findProvince(province) { 
    return province.name === '北京市';
}

console.log(province.find(findProvince)); 
//{areaCode: "1", name: "北京市"}
```

**Comment by huangxiaohao** [comment]
@xwenliang 感谢您的回复。

> ES2015已经原生支持了，写法类似于：

> let province = [
>     {areaCode: "1", name: "北京市"},
>     {areaCode: "2", name: "上海市"},
>     {areaCode: "3", name: "广州市"}
> ];
> 
> function findProvince(province) { 
>     return province.name === '北京市';
> }
> 
> console.log(province.find(findProvince)); 
> //{areaCode: "1", name: "北京市"}

您所说的这个方法，是在使用您的控件基础上，再去根据获取到的省／市名 `name` 去查找原始数据其对应的 `areaCode ` 吗？

**Comment by xwenliang** [comment]
是的...

**Comment by huangxiaohao** [comment]
@xwenliang 感谢提示，我想我已经实现我需要的功能了。
谢谢！
