### ISSUE TITLE
ios 中使用wheel时，不对称展示

### ISSUE THREAD

**Issue by sunny20131314** [beefe/react-native-picker#137]
![image](https://cloud.githubusercontent.com/assets/13795567/24997006/95f72870-2067-11e7-8f7a-b39266fba373.png)

相应版本：
"react": "^15.4.1",
"react-native": "^0.39.2",
"react-native-picker": "^4.0.18",

并且在init picker 时，传入了参数： wheelFlex: [1, 1], 但也设置无效

**Comment by Johnxc** [comment]
遇到了同样的问题，最终是通过设置wheelFlex权重解决的，wheelFlex: [0.324, 0.676]，这样第一列展示正常，第二列稍微有点偏；还可以把数据设置为三列，第三列不要放内容，这样展示正常，但中间会出现一些间距。希望对你有用。

**Comment by sunny20131314** [comment]
好的，谢谢，我看下哪个更适合
