### ISSUE TITLE
Cascade mode, three wheels, the 3rd wheel data is not refresh

### ISSUE THREAD

**Issue by sadikelong** [beefe/react-native-picker#14]
The test data is below, when I change the 2nd wheel, the data for 3rd wheel is always [1,2,3,4].
    pickerData = {
        a: {
            a1: [1,2,3,4],
            a2: [5,6,7,8],
            a3: [9,10,11,12]
        },
        b: {
            b1: [1,2,3,4],
            b2: [5,6,7,8],
            b3: [9,10,12,12]
        }
        ...
    };
    selectedValue = ['a', 'a1', 1];

**Comment by xwenliang** [comment]
```javascript
<Picker
	pickerHeight={320}
	showDuration={300}
	pickerData={{
		a: {
			a1: [1,2,3,4],
			a2: [5,6,7,8],
			a3: [9,10,11,12]
		},
		b: {
			b1: [1,2,3,4],
			b2: [5,6,7,8],
			b3: [9,10,12,12]
		}
	}}
	selectedValue={['a', 'a1', 1]}
	onPickerDone={(pickedValue) => {
		console.log(pickedValue);
	}}
/>
```
I tried this code on v0.3.5, everything seems normal on both iOS and android. can you paste your code?

**Comment by sadikelong** [comment]
![image](https://cloud.githubusercontent.com/assets/7940552/12535009/94ea6360-c2ae-11e5-98ab-2fbfe32181fb.png)
![mytest](https://cloud.githubusercontent.com/assets/7940552/12535011/a7360182-c2ae-11e5-9879-1bbdc073873c.gif)

**Comment by sadikelong** [comment]
Hi,xwenliang:
I test with v0.3.5, the Cascade mode work well. Thanks very much!
