### ISSUE TITLE
Picker.init shows the picker on iOS

### ISSUE THREAD

**Issue by vivaxy** [beefe/react-native-picker#145]

**Comment by mvdam** [comment]
I experience the same issue. When calling `Picker.init` only on iOS the picker is shown immediately. For now I fixed it by calling `Picker.hide()` after initialising the picker. Android version seems to work fine so far.

**Comment by sabonis** [comment]
+1

**Comment by wbattel4607** [comment]
+1

**Comment by xwenliang** [comment]
`v4.3.0` fixed it.
