### ISSUE TITLE
Cascade Mode February 31 Days Allowed

### ISSUE THREAD

**Issue by Sexycrets** [beefe/react-native-picker#15]
I tried to use the data-picker example and it works perfectly fine but February seems to allow more than 29 days although the 'for' cycle in the code seems to correctly go just to 29.

**Comment by xwenliang** [comment]
![b](https://cloud.githubusercontent.com/assets/3360560/12534963/b2993600-c2ab-11e5-94fd-714d29070138.jpg)

sorry for that , bug i don't kown how you can allow more than 29 days, check your pickerData?

**Comment by sadikelong** [comment]
Hi, xwenliang:
I think this issue is the same as the one I commit. The 3rd wheel data is not refresh. I test this case too.
I will paste my code.

**Comment by xwenliang** [comment]
take a look at this: https://github.com/beefe/react-native-picker/issues/14

**Comment by Sexycrets** [comment]
Thank you very much! It works
