### ISSUE TITLE
date-picker  demo  数据没有显示

### ISSUE THREAD

**Issue by AlexTMing** [beefe/react-native-picker#159]
![qq 20170522191014](https://cloud.githubusercontent.com/assets/21952704/26305581/7aa022c8-3f22-11e7-9144-49f6038d3736.jpg)
![qq 20170522191037](https://cloud.githubusercontent.com/assets/21952704/26305582/7ab82030-3f22-11e7-967c-5254e8b82409.jpg)
![qq 20170522191059](https://cloud.githubusercontent.com/assets/21952704/26305583/7ad1a820-3f22-11e7-8304-1c0facf4f5b7.jpg)

**Comment by xwenliang** [comment]
运行环境和RN版本贴一下

**Comment by xwenliang** [comment]
pickerData数据格式不对，它应该是个数组：
```javascript
[
    {
        a: [
            {
                a1: [1,2,3,4]
            },
            {
                a2: [5,6,7,8]
            },
            {
                a3: [9, 10, 11, 12]
            }
        ]
    },
    {
        b: [
            {
                b1: [1,2,3,4]
            },
            {
                b2: [5,6,7,8]
            },
            {
                b3: [9, 10, 11, 12]
            }
        ]
    }
]
```
