### ISSUE TITLE
[question] Event onPickerDone when wheels stop

### ISSUE THREAD

**Issue by Sexycrets** [beefe/react-native-picker#17]
This is not an issue, all works perfectly fine, just a question. Please let me know if I should write it somewhere else.

The onPickerDone event is fired when the pickerBtn is pressed.

In my case the react-native-picker is visible all the time in a form, with no bar (i.e. no pickerBtn or pickerCancel). The reason I did it this way is to remove friction in the UX. I would like the user to select the date and every time he changes any wheel an event (e.g. onPickerDone) to be fired.

This way I can update the state of my form component with the new date selected every time the user changes it and the user does not need to click any button to confirm his choice.

Do you have any suggestion on how I could achieve this?

Thank you very much in advance.

**Comment by xwenliang** [comment]
I add this param named `onValueChange` on new version 0.4.0  https://github.com/beefe/react-native-picker/commit/90451c371d70ef2d8ce5a3aab74932b6f4488120
It accepts two arguments `selectedValue` and `wheelIndex`
Remember to refresh your pickerData on this func, like this:
```javascript
<Picker
	ref={picker => this.picker = picker}
	pickerHeight={320}
	showDuration={300}
	pickerData={createDateData()}
	selectedValue={this.state.selectedValue}
	onPickerDone={(pickedValue) => {
		console.log(pickedValue);
	}}
	onValueChange={(selectedValue, index) => {
		//console.log(selectedValue, index);
		this.setState({
			selectedValue: selectedValue
		})
	}}
/>
```
Good luck!

**Comment by xwenliang** [comment]
Be care for the second param `wheelIndex`, on Cascade mode, the first wheel change may cause the second and third wheel change, the `wheelIndex` always direct to the last one that changed. 
But i think this doesn't matter much as you can get the whole selectedValue.

**Comment by Sexycrets** [comment]
Thank you @xwenliang it works like a charm! Yes, I will just read the selectedValue when the users submits the form so I'm good.

Just FYI, I did a console log on  ```selectedValue``` and ```index``` with
```
onValueChange={(selectedValue, index) => {
            console.log(selectedValue, index);            
          }}
```
and year and month seems to be returned as ```string``` while day seems to be a number, not a big deal, just wondering why:
```
["2013", "4", 11] 2
```

**Comment by xwenliang** [comment]
Check your pickerData, the data of day may be a number?
Like this [example](https://github.com/beefe/react-native-picker/blob/master/demo/date-picker.js#L29-L31), if we replace `day.push(k+'日')` to only `day.push(k)`, the data of day will be a number indeed.
All we need to do is just `k.toString()` instead. :)

**Comment by Sexycrets** [comment]
Awesome! Works perfectly, thanks.
