### ISSUE TITLE
是不是暂时还不支持pod的？

### ISSUE THREAD

**Issue by tianmingzhi** [beefe/react-native-picker#171]
项目中都是用pod管理的，picker引入pod会报错。。

pod 'react-native-picker', path: '../node_modules/react-native-network-picker'

**Comment by xwenliang** [comment]
暂不支持

**Comment by jeffy7** [comment]
iOSNative与RN混编，工程是用pod 管理，现在出现[#108](https://github.com/beefe/react-native-picker/issues/108)问题，怀疑是没有链接到libRCTBEEPickerManager，有解决思路么

**Comment by tianmingzhi** [comment]
@jeffy7 你试试手动加入工程里看能不能用，不清楚是不是我没配置好的原因，会编译不过。

**Comment by jeffy7** [comment]
你的这个思路就是分别给iOS以及Android封装组件，我正在尝试，直接用你的RCTBEEPickerManager与BzwPicker这两个类

**Comment by jeffy7** [comment]
我解决了这个问题，顺便解决了[#108](https://github.com/beefe/react-native-picker/issues/108)这个问题，直接拷贝出你的那四个文件，然后就可以运行，其他都是按照你的demo里面就行

**Comment by xwenliang** [comment]
感谢@troyz 提的 https://github.com/beefe/react-native-picker/pull/165
目前新版本`4.1.1`已支持
