### ISSUE TITLE
Why react-native-picker?

### ISSUE THREAD

**Issue by oliverbenns** [beefe/react-native-picker#176]
There's no mention on the README as to why I need this over the [standard picker](https://facebook.github.io/react-native/docs/picker.html). Would be good to include some more information. Is it just for multiple wheels?

**Comment by MunazR** [comment]
The standard picker works very differently for Android. On Android it only supports a dropdown or dialog.

**Comment by oliverbenns** [comment]
Yep, managed to work that out. Might be nice to have this in the Readme.
