### ISSUE TITLE
android 的 onPickerConfirm   onPickerCancel  onPickerSelect点击不执行方法为啥？

### ISSUE THREAD

**Issue by Flynana** [beefe/react-native-picker#177]
Picker.init({
            pickerData: data,
            pickerTitleText:'',
            selectedValue: [],
            pickerConfirmBtnText:'确定',
            pickerCancelBtnText:'取消',
            pickerToolBarBg:[224,224,224,1],
            pickerBg:[255,255,255,1],
            pickerConfirmBtnColor:[255,116,47,1],
            pickerCancelBtnColor:[255,116,47,1],
            onPickerConfirm: pickedValue => {
                alert('1111');
                console.log('area', pickedValue);
            },
            onPickerCancel: pickedValue => {
               alert('2222');
                console.log('area', pickedValue);
            },
            onPickerSelect: pickedValue => {
                 alert('3333');
                console.log('area', pickedValue);
            }
        });
        Picker.show();

android 的点击无效 alert 都不弹出  为什么吗？ 我的 picker 版本是4.0.19

**Comment by NidhoggC** [comment]
是否正确引入了组件？react native link后需要重启packager (提问尽量用英文)

**Comment by ocswor** [comment]
这个问题解决了么

**Comment by ocswor** [comment]
@iceOolongTea 能说清楚点么,是什么原因? 我也执行link了

**Comment by Flynana** [comment]
已经解决了，是我的react-native版本太低了，多谢
