### ISSUE TITLE
show error

### ISSUE THREAD

**Issue by xuefengyang** [beefe/react-native-picker#18]
I run your demo ,but the picker show [object Object]

**Comment by xwenliang** [comment]
demo只是几个picker的使用例子，不能直接运行，需要在具体项目中才能使用

**Comment by xuefengyang** [comment]
var PageContainer = React.createClass ({

    getInitialState :function(){
        return({
            pickerData: [{
              '北京': {
                '北京': ['朝阳区']
              }
            }],
          selectedValue: ['北京', '北京', '朝阳区']
        });
    },
    _onPressHandle :function(){
        this.picker.toggle();
      },
    render :function(){
        return (
          <View style={{height: Dimensions.get('window').height}}>
              <TouchableOpacity style={{marginTop: 20}} onPress={this._onPressHandle}>
              <Text>点我</Text>
            </TouchableOpacity>
              <Picker
                ref={picker => this.picker = picker}
                pickerHeight={320}
                showDuration={300}
                pickerData={this.state.pickerData}
                selectedValue={this.state.selectedValue}
                onPickerDone={(pickedValue) => {
                console.log(pickedValue);
                }}/>
          </View>
     );
    }

**Comment by xuefengyang** [comment]
我是这样写的

**Comment by xuefengyang** [comment]
道理说应该没有问题啊

**Comment by xwenliang** [comment]
@xuefengyang 
Cascade 模式下, pickerData 是个json而不是数组...
```javascript
getInitialState :function(){
    return({
        pickerData: {
          '北京': {
            '北京': ['朝阳区']
          }
        },
        selectedValue: ['北京', '北京', '朝阳区']
    });
}
```

**Comment by xuefengyang** [comment]
必须是数组类型的才可以吗？ @xwenliang

**Comment by xwenliang** [comment]
必须是key:value的object... 这块数据格式写的比较死
