### ISSUE TITLE
pickerData: this._createDateData() 这种方式只能支持到三级吗？

### ISSUE THREAD

**Issue by zhuchaoming** [beefe/react-native-picker#180]
Picker.init({
    pickerData: this._createDateData(),
    ...
});
在example/PickerTest第一个例子中的“年月日”下面加了一层“小时”，结果不显示

**Comment by xwenliang** [comment]
联动的 只支持三级

**Comment by xwenliang** [comment]
你可以看看这个栗子 [_showTimePicker](https://github.com/beefe/react-native-picker/blob/master/example/PickerTest/index.js#L115-L185)

**Comment by zhuchaoming** [comment]
这种用法，二月份会显示30、31，用户体验不大好
