### ISSUE TITLE
error when react native 0.47.1

### ISSUE THREAD

**Issue by tigerohuang** [beefe/react-native-picker#183]
node_modules/react-native-picker/android/src/main/java/com/beefe/picker/PickerViewPackage.java:24: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
1 个错误
:react-native-picker:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-picker:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by jimmy-devine** [comment]
It looks like there's a fix pending here: https://github.com/beefe/react-native-picker/pull/182

**Comment by xwenliang** [comment]
v4.1.1 已修复
