### ISSUE TITLE
如何更改下面wheel的布局大小，我注意到在index.js中有wheelFlex这么一个属性

### ISSUE THREAD

**Issue by XingXiaoWu** [beefe/react-native-picker#188]
wheelFlex，看名字应该是指下方滑轮的布局，但是我修改数值之后没有任何变化，因此有两个问题
1.wheelflex这个值代表的是哪项属性
2.如果要修改下方滑轮的布局大小应该修改哪项属性
谢谢lz大大

**Comment by xwenliang** [comment]
如果有3个滚轮，那么设置wheelFlex: [1, 2, 1] 就会让三个滚轮的宽度比例为 1：2：1
