### ISSUE TITLE
can't install via cocoapods b/c podspec doesn't have a homepage

### ISSUE THREAD

**Issue by amitailanciano** [beefe/react-native-picker#189]
looks like it's referencing the package.json homepage, adding a homepage there should fix the issue

<img width="510" alt="screen shot 2017-08-17 at 12 00 08 am" src="https://user-images.githubusercontent.com/1289466/29399697-164551da-82df-11e7-9785-9c85881ead8b.png">

**Comment by xwenliang** [comment]
`v4.1.2` published for this problem, thanks.
