### ISSUE TITLE
style={{height: Dimensions.get('window').height}}

### ISSUE THREAD

**Issue by Taakn** [beefe/react-native-picker#19]
Hello,

Great component. I'm just not understanding why you wrap your component in a view with `style={{height: Dimensions.get('window').height}}` which means that the remaining components coming after the picker are pushed outside of the screen.

How would you go about fixing that?

Thanks

**Comment by xwenliang** [comment]
I just want to make an animation for the Picker show, 
At first, make outer view `{{height: Dimensions.get('window').height}}`, and make the Picker
`{{bottom: 0, position: 'absolute'}}`, then we can slideUp the Picker when we clicked the 'show button'.
If you want to show Picker at first, you can change the style of outer view or style of Picker.

**Comment by Taakn** [comment]
@xwenliang what I am trying to say is that the components displayed after the picker get pushed back outside of the screen, because the outer view height _is_ the height of the screen.

So that's my question: how do you display components after the picker so they don't get pushed outside of the screen.

Thanks!

**Comment by Taakn** [comment]
I mean it works if you place the picker very last in the component list then you can have the button opening it anywhere, but is there another, more elegant way, than splitting up the two?

**Comment by xwenliang** [comment]
I add customized style support for the picker in [v0.4.1](https://github.com/beefe/react-native-picker/commit/034044eb0af71715919d33d079912bb807fac614), I have no idea if this could make sense for you.

![1](https://cloud.githubusercontent.com/assets/3360560/12778319/1af8d590-ca9d-11e5-9c98-f0974c181f40.jpg)

```javascript
render(){
	return (
		<View>
			<View style={{height: 100, paddingTop: 80, backgroundColor: 'red'}}>
				<Text>this is something above picker</Text>
			</View>
			<View style={{height: 240, position: 'relative', backgroundColor: 'green'}}>
				<Picker
					ref={picker => this.picker = picker}
					pickerHeight={240}
					showDuration={300}
					pickerData={createDateData()}
					selectedValue={['2015年', '12月', '12日']}
					onPickerDone={(pickedValue) => {
						console.log(pickedValue);
					}}
					style={{top: 0}}
					pickerToolBarStyle={{height: 0, opacity: 0}}
				/>
			</View>
			<View style={{height: 100, backgroundColor: 'yellow'}}>
				<Text>this is something below picker</Text>
			</View>
		</View>
	);
}
```

**Comment by Taakn** [comment]
Thanks I'm closing the issue.

**Comment by alexlevy0** [comment]
@xwenliang  Is it still possible to display the picker with a component on the bottom as in your image?
