### ISSUE TITLE
Can this picker have default value? 

### ISSUE THREAD

**Issue by wenwen1995** [beefe/react-native-picker#191]
I want to the Picker has default value,such  as get now year and month, 2017-08, not it appears from  1month to 12month,and let the user to select them,how could it do ?

**Comment by xwenliang** [comment]
try `selectedValue`

**Comment by wenwen1995** [comment]
Wa~Thank u! That's great，I try selectedValue and imitate your example in your demo,it works! Just like this:
![img_20170821_092425](https://user-images.githubusercontent.com/12100065/29500364-b1b9dc96-8652-11e7-851a-b489d3476fd8.png)
