### ISSUE TITLE
RN0.16.0中报错

### ISSUE THREAD

**Issue by Spikef** [beefe/react-native-picker#2]
在RN0.16.0中使用时，直接报错。
错误内容：
 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
代码：
<Picker pickerData={[1, 2, 3, 4]}  />

**Comment by Spikef** [comment]
<Picker pickerData={[1, 2, 3, 4]}  />

**Comment by sunnylqm** [comment]
多半是因为用了require语句
http://bbs.react-native.cn/topic/53/solved-componenet-hello-%E5%9C%A8android%E4%B8%8A%E7%9B%B4%E6%8E%A5%E6%8A%A5element-type-is-invalid/2

**Comment by Spikef** [comment]
楼上说得正确。
