### ISSUE TITLE
Change picker style

### ISSUE THREAD

**Issue by Sexycrets** [beefe/react-native-picker#20]
Hi, the 0.4.0 works great! How do you suggest I customize the style of the picker without changing your code in the node_modules folder?

In particular I would like to 

1. remove the background color so that it takes the one from my app
2. remove the pickerToolbar since I embedded it in a form

Changing your index.js I achieved what I wanted (attached) but all my changes will be lost every time I upgrade your package. 

Thanks!

![screen shot 2016-02-07 at 12 54 34 pm](https://cloud.githubusercontent.com/assets/13841380/12875204/fb528466-cd99-11e5-92b2-3a1a44ce37ce.png)

**Comment by xwenliang** [comment]
Take a look at this: [customized style support](https://github.com/beefe/react-native-picker/issues/19)
