### ISSUE TITLE
ios运行正常，安卓上面无法运行，不报错，点击picker.show()也不触发picker  ,怎么解决请告知

### ISSUE THREAD

**Issue by Gzbox** [beefe/react-native-picker#202]
_安卓的运行环境配置  根据教程配置了好几遍，反复确认没有遗漏的_

pickerData的选项滚轮为五个：年、月、日、时、分   
代码如下：  ios运行正常  安卓没有任何反应

` showTimePicker = () => {
    let years = [],
      months = [],
      days = [],
      hours = [],
      minutes = [];
    let today = new Date();//获得当前日期
    let year = today.getFullYear();//获得年份

    for (let i = 1; i < 5; i++) {
      years.push(`${i + year - 1}年`);
    }
    for (let i = 1; i < 13; i++) {
      months.push(`${i}月`);
    }
    for (let i = 1; i < 32; i++) {
      days.push(`${i}日`);
    }
    for (let i = 1; i < 24; i++) {
      hours.push(`${i}时`);
    }
    for (let i = 0; i < 60; i++) {
      minutes.push(`${i}分`);
    }

    let pickerData = [years, months, days, hours, minutes];
    let date = new Date();
    let selectedValue =
      [
        `${year}年`,
        `${date.getMonth() + 1}月`,
        `${date.getDate()}日`,
        `${date.getHours()}时`,
        `${date.getMinutes()}分`,
      ]

    Picker.init({
      pickerData,
      selectedValue,
      pickerTitleText: '请选择日期和时间',
      pickerConfirmBtnText: '确定',
      pickerCancelBtnText: '取消',
      wheelFlex: [2, 1, 1, 2, 1, 1],

      onPickerConfirm: pickedValue => {
        this.setState({
          selectValue: pickedValue
        })
      },

      onPickerCancel: pickedValue => {
        this.setState({
          selectValue: ''
        })
      },

      onPickerSelect: pickedValue => {
        let targetValue = [...pickedValue];
        if (parseInt(targetValue[1]) === 2) {
          if (targetValue[0] % 4 === 0 && targetValue[2] > 29) {
            targetValue[2] = 29;
          }
          else if (targetValue[0] % 4 !== 0 && targetValue[2] > 28) {
            targetValue[2] = 28;
          }
        }
        else if (targetValue[1] in { 4: 1, 6: 1, 9: 1, 11: 1 } && targetValue[2] > 30) {
          targetValue[2] = 30;

        }
        // forbidden some value such as some 2.29, 4.31, 6.31...
        if (JSON.stringify(targetValue) !== JSON.stringify(pickedValue)) {
          // android will return String all the time，but we put Number into picker at first
          // so we need to convert them to Number again
          targetValue.map((v, k) => {
            if (k !== 3) {
              targetValue[k] = parseInt(v);
            }
          });
          console.log('安卓没有成功？？')
          Picker.select(targetValue);
          pickedValue = targetValue;
        }
      }
    })

    Picker.show()
  }
`

**Comment by boyrt** [comment]
遇到和楼主差不多的问题。魅族手机：运行debug包没问题，运行release包，点击不弹出picker。华为手机没这问题。

**Comment by jianxinzhoutiti** [comment]
需要APP打开悬浮窗权限,在权限管理里面设置

**Comment by pentakill666** [comment]
你们都解决了吗

**Comment by pentakill666** [comment]
我们的有个测试机弹出来了，但是不能滑动，还有这个最多只能选择三级，不适用日期加小时和分钟，

**Comment by xwenliang** [comment]
把你们的安卓版本，RN版本以及使用的picker版本贴一下
