### ISSUE TITLE
How to close the app when tap outside the picker box?

### ISSUE THREAD

**Issue by stratiumsoftwaregroup** [beefe/react-native-picker#206]
How to close the app when tap outside the picker box? Please help. Thank you very much..

**Comment by ycb0318** [comment]
+1

**Comment by h2oiswater** [comment]
+1

**Comment by xwenliang** [comment]
`Picker.hide()`

**Comment by lukewlms** [comment]
There are a few threads on this - this solution with react-native-modal was easy and is working well for us.  https://github.com/beefe/react-native-picker/issues/162#issuecomment-376562920
