### ISSUE TITLE
I can't use this picker

### ISSUE THREAD

**Issue by zhangchunyu2016** [beefe/react-native-picker#207]
oh..browser tells me 
```
Cannot read property '_init' of undefined
```

**Comment by zhangchunyu2016** [comment]
anybody know why?

**Comment by zhangchunyu2016** [comment]
uh.. i forget  Step 2.

**Comment by BricePissard** [comment]
For those of you who were not able to link the lib through ```react-native link```
and get the error:
```javascript
Cannot read property '_init' of undefined
```

The classical manual library linking workflow is:

1. left-click on your project ```Library``` and ```"Add File to xxx"```
![screen shot 2017-12-14 at 11 03 47 am](https://user-images.githubusercontent.com/4115874/33986918-667e30ac-e0bf-11e7-9cdf-2c1601cfcf30.png)


2. In your project go to ```Build Settings``` search for ```Header Search Path```
 ![screen shot 2017-12-14 at 11 04 13 am](https://user-images.githubusercontent.com/4115874/33986992-a797d0e8-e0bf-11e7-92b8-e4a5031ad66c.png)
![screen shot 2017-12-14 at 11 04 47 am](https://user-images.githubusercontent.com/4115874/33987105-fdc03b22-e0bf-11e7-896c-80aca4469f1e.png)
and add a line ```$(SRCROOT)/../node_modules/react-native-picker/ios```


3. In your project go to ```Build Phase``` in the section ```Link Binary With Libraries```
![screen shot 2017-12-14 at 11 05 16 am](https://user-images.githubusercontent.com/4115874/33987185-4bcc7588-e0c0-11e7-8f1f-8d8d885a411d.png)
and add the file ```libRCTBEEPickerManager.a```

**Comment by beausmith** [comment]
I had this error too and later (in the shower) realized that I needed to close and then restart (run) my app due to the linked files. D'oh!
