### ISSUE TITLE
RN 48.1+ Redefinition of RCTMethodInfo issue

### ISSUE THREAD

**Issue by ssomnoremac** [beefe/react-native-picker#208]
After upgrading project to react-native 0.48.0 (0.48.1) , project doesn't compile anymore
Error: Redefinition of RCTMethodInfo

Issue seems to be related with [facebook/react-native#15775](https://github.com/facebook/react-native/issues/15775)

**Comment by luisfuertes** [comment]
I have this issue with RN v0.48.3

**Comment by ssomnoremac** [comment]
@luisfuertes , yup, just use my branch as referenced in #209 for now

**Comment by himrocks33** [comment]
@ssomnoremac Any idea when this will be merged into master?  Wasted all day Friday attempting to get master to work in project, then I came across this issue.  Your branch works great btw.  Thank you.

**Comment by ssomnoremac** [comment]
I'll update the PR in a second.

**Comment by xwenliang** [comment]
Thanks for all of you, new version resolved this problem.
