### ISSUE TITLE
need more methods

### ISSUE THREAD

**Issue by paulbao** [beefe/react-native-picker#21]
Could you please also add dismiss method like
`	dismiss(){
		this._slideDown();
	}`

This is useful when there are more than one Pickers. Need to dismiss others

**Comment by xwenliang** [comment]
Sorry to reply so late to you, new version [1.0.0](https://github.com/beefe/react-native-picker/commit/9784b210d00af8bbab0b48aa7c71c9be9d534cba) is published.
I have added some methods, `show` to show picker, `hide` to hide picker, and `isPickerShow` to check if the picker was visible.
