### ISSUE TITLE
求一个全国省市区的json文件

### ISSUE THREAD

**Issue by Geforceyu** [beefe/react-native-picker#210]

**Comment by pingxiaodou** [comment]
[area.txt](https://github.com/beefe/react-native-picker/files/1298949/area.txt)

初始化时稍微改一下
`let data = [];
        let len = area.length;
        for (let i = 0; i < len; i++) {
            let city = [];
            for (let j = 0, cityLen = area[i]['city'].length; j < cityLen; j++) {
                let _city = {};

                _city[area[i]['city'][j]['name']] = area[i]['city'][j]['area'].map(v => v.name);
                city.push(_city);
            }

            let _data = {};
            _data[area[i]['name']] = city;
            data.push(_data);
        }
        return data;`

**Comment by Geforceyu** [comment]
非常谢谢，现在我这里还需要选中后拿到省市区的编码，请教下怎么弄呢

**Comment by Geforceyu** [comment]
请问下点击确定按钮后回调的data里面只有省市区的名称，能不能回调省市区的编码给我呢，谢谢
