### ISSUE TITLE
miui9  小米5 弹不出来

### ISSUE THREAD

**Issue by sheepmiee** [beefe/react-native-picker#211]
模拟器（nexus 5x） 红米4A（miui8） 运行没问题，小米5（miui9）点击不能弹出，也不会报错，权限都给了，不知道问题出在哪里，能不能解决

**Comment by wwwqdsj** [comment]
顶一下，我也遇到了。

**Comment by travelgeezer** [comment]
@sheepmiee  [#219](https://github.com/beefe/react-native-picker/pull/219)
我尝试把 type 改成 application 是可以弹出来..  toast 级别好像不够.. 23333

**Comment by Sura-zm** [comment]
系统设置->授权管理->应用权限管理->{找到对应的应用}->显示悬浮窗    然后将权限设置为允许。我是用过这种方式解决的。

**Comment by xwenliang** [comment]
duplicate with #214
