### ISSUE TITLE
日期三级联动初始化selectedValue无效

### ISSUE THREAD

**Issue by zhiyingzzhou** [beefe/react-native-picker#223]
pickerData格式: 
![image](https://user-images.githubusercontent.com/16408285/31119764-a7081292-a7f7-11e7-949a-a9027d7db738.png)
init中的selectedValue值为[2017,10,3];
在应用中显示的却是 2017-10-1:
![image](https://user-images.githubusercontent.com/16408285/31119918-477d17ae-a7f8-11e7-854a-ce06fe381ae4.png)
环境:
OS: macOS Sierra 10.12.6
node: v8.6.0
react: 16.0.0,
react-native: 0.47.1,
Xcode: Version 9.0 (9A235)

**Comment by mengqingmeng** [comment]
把数值从大到小排列，貌似可以解决这个问题，你可以试试；例如：年月日都从大到小排列
