### ISSUE TITLE
How to use two pickers in one page?

### ISSUE THREAD

**Issue by 1335382915** [beefe/react-native-picker#224]
Thank you for providing such a good component. I find that when using two pickers in one page, they all refer to the same object, the pickerData will be contaminated, using lodash's `_.cloneDeep(Picker)` doesn't work.

**Comment by xwenliang** [comment]
This was not supported by now, sorry.

**Comment by adon94** [comment]
I had the same issue so I re-initialized the same Picker every time I needed it but using different data and on confirm methods for each. Seems to work ok for me.

**Comment by xwenliang** [comment]
> I re-initialized the same Picker every time I needed it but using different data and on confirm methods for each. 

 maybe the best solution.
