### ISSUE TITLE
Data display Problems in android

### ISSUE THREAD

**Issue by TangMiao** [beefe/react-native-picker#225]
Version：
  "react-native": "^0.46.4",
  "react-native-picker": "^3.0.5",
---

Code：
<pre>
import Picker from 'react-native-picker';
import areaData from '../../../assets/area.json';
function createAreaData(area) {
	let data = {};
	let len = area.length;
	for (let i = 0; i < len; i++) {
		let city = area[i]['city'];
		let cityLen = city.length;
		let ProvinceName = area[i]['name'];
		data[ProvinceName] = {};
		for (let j = 0; j < cityLen; j++) {
			let area = city[j]['area'];
			let cityName = city[j]['name'];
			data[ProvinceName][cityName] = area;
		}
	}
	return data;
};
class test extends Component {
	constructor(props, context) {
		super(props, context);
		this.state = {
		         province: '北京',
			 city: '北京',
			 region: '朝阳区',
			pickerData: [{
				'北京': {
					'北京': ['朝阳区']
				}
			}],
			selectedValue: ['北京', '北京', '朝阳区']
		};
	}

	componentWillMount() {
		this.setState({
			pickerData:  createAreaData(areaData)
		});
	}

	onPressHandle() {
		this.picker.toggle();
	}
	onHidePicker(){
		this.picker.hide()
	}
	onChangeArea(pickedValue) {
		this.setState({
			 province: pickedValue[0],
			 city: pickedValue[1],
			 region: pickedValue[2]
		})
	}
render() {
       return(
        View
	TouchableOpacity onPress={this.onPressHandle.bind(this)}
		<Text>点击测试</Text>
	TouchableOpacity

	Picker
		ref={picker => this.picker = picker}
		showDuration={150}
		showMask={true}
		pickerBtnText="确认"
		pickerCancelBtnText="取消"
		pickerToolBarStyle={{backgroundColor: '#04bdbf'}}
		textStylePropType={{color: '#ffeeee'}}
		viewStylePropType={{backgroundColor: '#fff'}}
		pickerData={this.state.pickerData}
		selectedValue={this.state.selectedValue}
		onPickerDone={(pickedValue) => this.onChangeArea(pickedValue)}
	/>
       View
)}
}

----

area.json format
<pre>
[
	{
		"name": "北京",
		"city": [
			{
				"name": "北京",
				"area": [
					"东城区",
					"顺义区",
					"昌平区",
					"大兴区",
					"平谷区",
					"怀柔区",
					"密云县",
					"延庆县"
				]
			}
		]
	},
	{
		"name": "天津",
		"city": [
			{
				"name": "天津",
				"area": [
					"和平区",
					"河东区",
				]
			}
		]
	},
]

</pre>

![wx20171014-111614](https://user-images.githubusercontent.com/31785440/31572125-42ba0ce4-b064-11e7-8d71-7bfc09cc248e.png)

**Comment by xwenliang** [comment]
这个版本已经不再维护了，建议使用最新版本：）
