### ISSUE TITLE
Menu option is empty on android

### ISSUE THREAD

**Issue by Ali-Dalal** [beefe/react-native-picker#229]
`<Picker
                        ref={picker => this.picker = picker}
                        style={{height: 320}}
                        showDuration={300}
                        pickerData={["Male", "Female", "Not Set"]}
                        selectedValue={this.state.gender}
                        onPickerDone={(pickedValue) => {
                            this.setState({gender: pickedValue});
                        }}
                    />`

When I use the previous code, It works perfect on IOS, but in android, I always get empty list

**Comment by xwenliang** [comment]
`Picker` was a Module more than a Component, so we use it like this:
`Picker.init(options)`

**Comment by MrMeiyu** [comment]
@xwenliang 请问一下picker的整体高度怎么设置？
