### ISSUE TITLE
Done button hidden if loaded in landscape

### ISSUE THREAD

**Issue by jimthedev** [beefe/react-native-picker#23]
Hi there. Great plugin! I've located what I think is a bug. Specifically it happens if you have a device in landscape when you open the app but later rotate into portrait. It happens on both iOS and Android.

Here is a shot of the problem in action:

![screen shot 2016-02-16 at 4 45 54 pm](https://cloud.githubusercontent.com/assets/108938/13093819/dec9c680-d4cc-11e5-97fe-252fafc02acb.png)

**Comment by xwenliang** [comment]
Good issue! But i have no time to fix this bug in the near term...
I will greatly appreciate your PR :)

**Comment by jimthedev** [comment]
I'll see what I can do. :D

**Comment by jimthedev** [comment]
@xwenliang One quick question. I know this implementation advertises itself as pure JS, but in order to get proper orientation support in react native, I'd need to add a [native orientation listener](https://www.npmjs.com/package/react-native-orientation). Is this a deal breaker for this project or would you accept a PR with this as a new dependency? I can fork if needed, but I was hoping not to.

**Comment by xwenliang** [comment]
I will accept your PR with new dependency, thank you in advance for your good work!
If some others have single orientation can ignore the native code, i think it is not a big problem.

**Comment by jimthedev** [comment]
@xwenliang Ok thanks for the feedback. I've opted not to include a new dependency in this project. 

Instead, people can use react-native-orientation in their app project then pass the width that they want into the picker on an orientation change. To support this, I've added a prop called pickerWidth. If you don't supply this, then the current functionality should continue. PR incoming soon.

**Comment by xwenliang** [comment]
:+1: Great work! 
I think this is the best solution for this issue. Thank you very much. `v1.1.0` published

**Comment by jimthedev** [comment]
Thanks for the quick merge and publish!
