### ISSUE TITLE
pickerIndex is undefined 

### ISSUE THREAD

**Issue by AFMW** [beefe/react-native-picker#231]
On IOS when I select an item and confirm it the pickedIndex value its undefined, why is it undefined?

Picker.init({
              pickerData: data,
              pickerToolBarFontSize: 16,
              pickerFontSize: 18,
              pickerFontColor: [255, 0 ,0, 1],
              pickerBg: [255, 255 ,255, 1],
              pickerToolBarBg: [243, 243 ,245, 1],
              pickerConfirmBtnColor: [14, 39 ,54, 1],
              pickerCancelBtnColor: [14, 39 ,54, 1],
              pickerConfirmBtnText:"Aplicar",
              pickerCancelBtnText:"Cancelar",
              pickerTitleText:"",
              pickerFontColor: [0, 0 ,0, 1],
              onPickerConfirm: (pickedValue, pickedIndex) => {
               
                  //   json_nuevoInmueble.body.garages = parseInt(pickedValue[0]);
                  
                  console.log(pickedValue +" "+ pickedIndex)

                  this.setState({'proyectoAgente':pickedValue})
                  
                  console.log(json_nuevoAgente)
              },
              onPickerCancel: (pickedValue, pickedIndex) => {
              },
              onPickerSelect: (pickedValue, pickedIndex) => {

              }
          });
          Picker.show();

My package versions are: 
"react-native": "0.42.0",
"react-native-picker": "^4.0.18",

**Comment by xwenliang** [comment]
Sorry I can't reproduce it. If there are anyone else has the same issue, i will reopen it.
