### ISSUE TITLE
ios 无法运行

### ISSUE THREAD

**Issue by LIZHIBIN513** [beefe/react-native-picker#233]
Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/PickerTest.app/Info.plist

**Comment by xwenliang** [comment]
是直接运行的[Example](https://github.com/beefe/react-native-picker/tree/master/example/PickerTest)里的代码吗？可能版本比较低的原因，建议使用`react-native init`重新生成项目，然后拷贝[Example](https://github.com/beefe/react-native-picker/tree/master/example/PickerTest)的逻辑代码进去再运行:)
