### ISSUE TITLE
安卓如果地区显示太长的话，显示不全

### ISSUE THREAD

**Issue by madarong** [beefe/react-native-picker#238]
![image](https://user-images.githubusercontent.com/26993188/33112453-45da629a-cf8e-11e7-8574-8cd23b43c66b.png)

**Comment by zhangleiwant** [comment]
源码里面可以处理的，在node_modules里面找到react-native-picker，找到android下面的com.beefe.picker.view.LoopView修改里面的getX()方法，
 private float getX(String text, Paint paint) {
        paint.getTextBounds(text, 0, text.length(), tempRect);
        //return (getWidth() - tempRect.width() * scaleX) / 2;
        if((getWidth() - tempRect.width() * scaleX) / 2 > 0){
            return (getWidth() - tempRect.width() * scaleX) / 2;
        }else{
            return 0;
        }
    }
在onDraw()方法中可以加上
 if(text.length()>7){
                        canvas.drawText(text.substring(0,7)+"...", getX(text, paintCenterText), getY(paintCenterText), paintCenterText);
                    }else{
                        canvas.drawText(text, getX(text, paintCenterText), getY(paintCenterText), paintCenterText);
                    }

**Comment by madarong** [comment]
好了，大神太感谢了



1542265532@qq.com
 
发件人： zhangleiwant
发送时间： 2018-01-03 11:26
收件人： beefe/react-native-picker
抄送： madarong; Author
主题： Re: [beefe/react-native-picker] 安卓如果地区显示太长的话，显示不全 (#238)
源码里面可以处理的，在node_modules里面找到react-native-picker，找到android下面的com.beefe.picker.view.LoopView修改里面的getX()方法，
private float getX(String text, Paint paint) {
paint.getTextBounds(text, 0, text.length(), tempRect);
//return (getWidth() - tempRect.width() * scaleX) / 2;
if((getWidth() - tempRect.width() * scaleX) / 2 > 0){
return (getWidth() - tempRect.width() * scaleX) / 2;
}else{
return 0;
}
}
在onDraw()方法中可以加上
if(text.length()>7){
canvas.drawText(text.substring(0,7)+"...", getX(text, paintCenterText), getY(paintCenterText), paintCenterText);
}else{
canvas.drawText(text, getX(text, paintCenterText), getY(paintCenterText), paintCenterText);
}

**Comment by xwenliang** [comment]
新添加了`pickerTextEllipsisLen`参数，支持设置超过多少字显示'...'

**Comment by madarong** [comment]
太好了，谢谢啦


1542265532@qq.com
 
发件人： zooble
发送时间： 2018-01-10 19:41
收件人： beefe/react-native-picker
抄送： madarong; Author
主题： Re: [beefe/react-native-picker] 安卓如果地区显示太长的话，显示不全 (#238)
新添加了pickerTextEllipsisLen参数，支持设置超过多少字显示'...'
