### ISSUE TITLE
选择当前时间

### ISSUE THREAD

**Issue by LIZHIBIN513** [beefe/react-native-picker#243]
example/PickerTest/PickerTest.js中,调用_showDatePicker 方法，init中配置 selectedValue选项为当前时间，第一次打开显示的当前日期不对，总是为每一月的第一天。

**Comment by xwenliang** [comment]
要注意传入的`selectedValue`必须能在你的`pickerData`中完全对应，包括类型，如果使用的是我写的数据，那我想数据格式应该是这样的：
`selectedValue: ['2017年', '12月', '11日']`
