### ISSUE TITLE
Cascade mode

### ISSUE THREAD

**Issue by ozsirma** [beefe/react-native-picker#244]
I need cascade picker because of get last six months. What is your suggestion for this topic ? 
Example:
July
August
October.               **2017**
November
December

January                **2018**

**Comment by xwenliang** [comment]
How about single wheel? Just show as you wrote.

**Comment by ozsirma** [comment]
Not a single wheel. This topic include two wheels. First wheel is months, second wheel is years.

**Comment by xwenliang** [comment]
Sorry, data of Picker could not change unless init again. But maybe you can try parallel 
 mode and use `Picker.select` to control the selectedValue:
```javascript
onPickerSelect: pickedValue => {
    const targetValue = [...pickedValue];
    //only last six months avalible for 2017
    if(parseInt(targetValue[0] < 6 && targetValue[1]) === 2017){
        //reset to july
        targetValue[0] = 6;
        Picker.select(targetValue)
    }
}
```

**Comment by ozsirma** [comment]
It is worked. Thank you.
