### ISSUE TITLE
Wrong height when init-ing more than once, with a different height.

### ISSUE THREAD

**Issue by SudoPlz** [beefe/react-native-picker#248]
I'm using the picker in 2 different places in my code, and basically the only thing that changes is the `pickerData` I pass to it.

When the picker opens up for the first time all looks good:
<img width="1648" alt="screen shot 2017-12-14 at 20 34 36" src="https://user-images.githubusercontent.com/3070948/34008506-3e83af74-e10e-11e7-8095-2ae46a18fd30.png">

but when the picker opens up the second time, the title bar is hidden:
<img width="1609" alt="screen shot 2017-12-14 at 20 34 29" src="https://user-images.githubusercontent.com/3070948/34008515-4513f7cc-e10e-11e7-8df7-8169f2091043.png">

I'm using:
    react-native-picker: 4.3.0
    react-native: 0.49.5 

and that ONLY happens on **Android**! (Not on iOS)

**Comment by xwenliang** [comment]
Thanks for your issue and PR 👍

**Comment by SudoPlz** [comment]
Thanks for merging so fast! 👍  Will you also publish to npm?

**Comment by AnagramEngineering** [comment]
It seems this change was merged but removed in a later commit. At least this is not working for me in 4.3.5 (and also the code looks like before the commit)

**Comment by SudoPlz** [comment]
Hmm, that's true, I don't see my code in master.. @xwenliang any ideas?

**Comment by AnagramEngineering** [comment]
It was removed in

**Comment by SudoPlz** [comment]
Interesting, but why :O ?

**Comment by AnagramEngineering** [comment]
Good question. 

I'm experiencing the same problem as you did and can confirm that everything is working fine after integrating your code changes. 

Unfortunately for now i have to take care of them manually ...

**Comment by AnagramEngineering** [comment]
@xwenliang  any updates on this? This ticket should be reopened ...

**Comment by congshengwu** [comment]
Thank you for your PR, I also have this issue, and your code is working fine on my side. I have changed the code locally as this patch commit was not merged to the master branch. Although this thread has been a long time, thank you for saving me time.
