### ISSUE TITLE
call Picker.select['xxx']选中一个值，点开picker后，随便选中一个其它值，点确定按钮依然返回的是前面方法指定的值

### ISSUE THREAD

**Issue by luchun-bees360** [beefe/react-native-picker#250]
call Picker.select['xxx'], click of confirm button is not current select value

**Comment by scutHuqiang** [comment]
碰到了同样的问题，请问最后是怎么解决的？

**Comment by EliteCRM** [comment]
ios/RCTBEEPickerManager/RCTBEEPickerManager.m 
@@ -130,7 +130,7 @@ + (BOOL)requiresMainQueueSetup
    if (self.pick) {
        dispatch_async(dispatch_get_main_queue(), ^{
            _pick.selectValueArry = data;
            _pick..backArry = data;
            _pick.backArry = data;
            [_pick selectRow];
        });
    }return;
