### ISSUE TITLE
 Picker.isPickerShow 

### ISSUE THREAD

**Issue by LIZHIBIN513** [beefe/react-native-picker#256]
Picker.isPickerShow  怎么用？

**Comment by LIZHIBIN513** [comment]
Picker.isPickerShow 怎么用啊

**Comment by LIZHIBIN513** [comment]
控件中 isPickerShow 方法怎么用，源码中需要一个回调fn？但是还想返回的都是false,有空麻烦看一下吧

**Comment by xwenliang** [comment]
```javascript
Picker.isPickerShow(status => {
    alert(status);
});
```

**Comment by zuijiusi** [comment]
> 
> 
> ```js
> Picker.isPickerShow(status => {
>     alert(status);
> });
> ```

cool
