### ISSUE TITLE
add ability to cancel the picker by tapping in the rest of the screen

### ISSUE THREAD

**Issue by jimthedev** [beefe/react-native-picker#26]
On iOS when a picker is activated, you can tap outside of the picker and it will cancel the picker. This would be a nice feature if we could put a transparent TouchableNoFeedback that cancels the picker when clicked.

**Comment by xwenliang** [comment]
I removed `pickerHeight` and `pickerWidth` in `v2.0.1` because we can set both of them in `style` prop, and I also add `showMask` to satisfy this requirement. I have no idea if my change will cause new bugs when orientation changed. Write them here if there are some :D

**Comment by jimthedev** [comment]
Ok I will give it a try this week to see if it works with the new changes.

**Comment by jimthedev** [comment]
@xwenliang Thanks. This worked perfectly. The only difference was that I needed to provide a background color for the picker since the default was now transparent. It looks and works great. :+1:

**Comment by xwenliang** [comment]
OK, thanks for your feedback, I will give it a default backgroundColor in later version.

**Comment by xwenliang** [comment]
`v2.0.2` published with default backgroundColor `#bdc0c7`

**Comment by jimthedev** [comment]
:+1:

**Comment by lukewlms** [comment]
Easy solution with react-native-modal: https://github.com/beefe/react-native-picker/issues/162#issuecomment-376562920
