### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by Bob1993** [beefe/react-native-picker#28]
While I use the Picker , something happened like this ![](http://ww1.sinaimg.cn/large/005zU9b3gw1f1930k2ze0j30h90uoafi.jpg)

```
          <TouchableOpacity style={{height: 40, flex: 1}} onPress={this._onPressHandle.bind(this)}>
            <Text>点我</Text>
          </TouchableOpacity>
          <Picker
            ref={picker => this.picker = picker}
            pickerHeight={300}
            showDuration={300}
            showMask={true}
            pickerData={['Hello', 'world']} //picker`s value List
            selectedValue ={'world'}
            onPickerDone={(pickedValue) => {
            console.log(pickedValue) }
          }/> //default to be selected value
```
Above all is my demo , anything wrong ? (function _onPressHandle is ok)

**Comment by Bob1993** [comment]
Is there some wrong with your library? I can't even  get anything with the demo provided in this repository....

**Comment by jimthedev** [comment]
@Bob1993 Take out the comments. // Style comments will break in JSX.

**Comment by xwenliang** [comment]
@jimthedev :+1:

**Comment by Bob1993** [comment]
@xwenliang  你在repo里的Demo没有写全吧？我直接拷进去运行是只有一个按钮，点击后什么也出不来

**Comment by xwenliang** [comment]
抱歉，Demo里面有个API改了忘记更新了，pickerHeight放到style里面设置了
已发布新版本修复 https://github.com/beefe/react-native-picker/commit/743677cb47539ed10289f732d928045017cd9a76

**Comment by Bob1993** [comment]
@xwenliang ....やめで... 刚刚把控件写完...

**Comment by xwenliang** [comment]
:+1:
