### ISSUE TITLE
undefined is not an object (evaluating 'Picker._init'). on iOS and Android, with Expo Project

### ISSUE THREAD

**Issue by kevinscience** [beefe/react-native-picker#289]
发生undefined is not an object (evaluating 'Picker._init').
init: index.js:33:15
两个操作系统都有这个问题。
使用在Expo project里。已经执行了react-native link，但是问题还是存在。请问有任何办法吗？

**Comment by lexuanquynh** [comment]
same issure

**Comment by hiradarshadi** [comment]
@lexuanquynh I have the same problem. But it doesn't work for me. At first I used react-native link but As you said you should do it manually, I checked the build.gradle and setting.gradle and ... and I saw that everything was written properly. The package was successfully linked

**Comment by lexuanquynh** [comment]
@hiradarshadi please show me a image for your problem.
Maybe in your project has a different config to run it.

**Comment by wLove-c** [comment]
在expo的项目中 是因为不能react-native link吗  导致 " Connot read property _ init of undefined"

**Comment by kevinscience** [comment]
Expo project cannot use any project which is required react-native link.

**Comment by vitozyf** [comment]
> same issure. you cann't use react-native link.
> 
> how to fix:
> in ios:
> open your Podfile and add:
> pod 'Picker', :path => '../YOUR_REACT_NATIVE_PROJECT/node_modules/react-native-picker' //you should custom your path here.
> 
> and run project.
> and add libPicker.a to your project. (open general tab and go to "Linked Frameworks and Libraries", add + button . )
> 
> in android:
> add to settings.gradle:
> include ':react-native-picker'
> project(':react-native-picker').projectDir = new File(rootProject.projectDir, 'YOUR_REACT_NATIVE_PROJECT/node_modules/react-native-picker/android') //you should custom your path here.
> and add to App:
> compile project(':react-native-picker')
> and run your project.
> 
> enjoy 💯

i can't find libPicker.a
