### ISSUE TITLE
Support value objects

### ISSUE THREAD

**Issue by jimthedev** [beefe/react-native-picker#29]
Hi,

Me again. :) One great feature for this plugin would be the ability to pass in an object:

```
[
  {
    label: 'One'
    value: 1,
  },
  {
    label: 'Two'
    value: 2,
  },
  {
    label: 'Two'
    value: 3,
  },
],
```

Then be able to specify a selector to use as the label that is shown to the user. When selected, the entire object would be returned. This way you could have hidden data in the selector.

**Comment by xwenliang** [comment]
OK, i will try to support this feature in a later time :D

**Comment by emiraydin** [comment]
+1

**Comment by af7** [comment]
+1, I actually needed this a lot, I had to create my own hash tables in order to show friendly names with 'unfriendly' values.

**Comment by xwenliang** [comment]
Thanks all of you.
It was easy to extend this feature in Parallel Mode, but the data was very complex in Cascade Mode, are there any good idea?  
An example of data for this feature in cascade mode:
```javascript
[
	{
		label: 'a',
		value: 'value of a',
		children: [
			{
				lable: 'a-a',
				value: 'value of a-a',
				children: [
					{
						lable: 'a-a-a',
						value: 'value of a-a-a'
					},
					{
						lable: 'a-a-b',
						value: 'value of a-a-b'
					}
				]
			},
			{
				label: 'a-b',
				value: 'value of a-b',
				children: [
					{
						lable: 'a-b-a',
						value: 'value of a-b-a'
					},
					{
						lable: 'a-b-b',
						value: 'value of a-b-b'
					}
				]
			}
		]
	},
	{
		label: 'b',
		value: 'value of b',
		children: [
			{
				lable: 'b-a',
				value: 'value of b-a',
				children: [
					{
						lable: 'b-a-a',
						value: 'value of b-a-a'
					},
					{
						label: 'b-a-b',
						value: 'value of b-a-b'
					}
				]
			},
			{
				label: 'b-b',
				value: 'value of b-b',
				children: [
					{
						lable: 'b-b-a',
						value: 'value of b-b-a'
					},
					{
						label: 'b-a-b',
						value: 'value of b-b-b'
					}
				]
			}
		]
	}
]
```

**Comment by DennisMG** [comment]
@xwenliang it would be perfect if you could push this feature! :) please!!

**Comment by luisfuertes** [comment]
It is already possible set value objects like OP example?

**Comment by dqisme** [comment]
You can just return a cascade index array as the value for mapping the `pickerData`. Like `itemPosition` as the `onValueChange` callback parameter in React Native picker [here](https://facebook.github.io/react-native/docs/picker.html#onvaluechange)

@xwenliang

**Comment by xwenliang** [comment]
@dqisme this feature now has been supported :)

**Comment by hugomosh** [comment]
Can you explain how it works, please?

**Comment by Taakn** [comment]
Doesnt look like this has actually been implemented

**Comment by charlot567** [comment]
@xwenliang It's doesn't seem to work on iOS. Is it normal?

**Comment by ozsirma** [comment]
I guess object support development is pending. @xwenliang

**Comment by david0u0** [comment]
看起來似乎沒有實作出這個功能? 將 [{"value": 1, "label": "標籤"}] 這類資料作為 pickerDate，會報出一個

Exception '-[__NSCFString firstObject]: unrecognized selector sent to instance XXXX' was thrown while invoking _init on target BEEPickerManager

感謝

**Comment by aprilmintacpineda** [comment]
Item supported but I don't see it in the docs.

**Comment by xxj95719** [comment]
支持一哈自定义属性哈
