### ISSUE TITLE
Text get cut off

### ISSUE THREAD

**Issue by oferRounds** [beefe/react-native-picker#291]
<img width="411" alt="screen shot 2018-03-15 at 10 55 09" src="https://user-images.githubusercontent.com/1477963/37453124-6662a432-283f-11e8-95ea-b74c710eb894.png">

How can this be solved?

**Comment by wswoodruff** [comment]
That's on Android correct? I had to do a different solution for Android because of this...

**Comment by oferRounds** [comment]
Yes, correct – on Android. What was the solution you did?

**Comment by ngdlmk** [comment]
Add your picker options pickerTextEllipsisLen value and give it a text length.

**Comment by oferRounds** [comment]
@ngdlmk Cool, thanks! It worked! :)

**Comment by hasaxena** [comment]
@ngdlmk @oferRounds Could you share an example of how you did that?

**Comment by oferRounds** [comment]
Hi @hasaxena 
Just add the property `pickerTextEllipsisLen` to object that initialize the picker with a big value, say: `300`.
