### ISSUE TITLE
关于Picker组件弹出位置的一点疑问

### ISSUE THREAD

**Issue by zhaotai** [beefe/react-native-picker#30]
我希望在表单中使用这个组件，就像select一样，选择，然后弹出Picker，但我发现，一旦把Picker包在一个单独的组件中，比如写在View中，它的底部会以这个组件的底部为基准，而不是以屏幕的底部为基准，请问我如何能做到，即把Picker封装到select组件中，同时让他以屏幕低端为基准slide up and slide down。

**Comment by xwenliang** [comment]
>Everything is position: relative. This makes position: absolute target the direct parent and not some parent which is either relative or absolute. If you want to position an element relative to something else, you should move it in the DOM instead of relying of CSS. It also makes top, left, right, bottom do something when not specifying position: absolute.  

https://github.com/facebook/css-layout  
看来目前还不能通过设置position的方式来实现，只能曲线救国了，可以试试把你的带picker的组件做成一个mixin
