### ISSUE TITLE
Unable to view picker data.

### ISSUE THREAD

**Issue by medetcan** [beefe/react-native-picker#317]
My package.json configuration as follows;
`
{
    "react-native-picker": "^3.0.5",
     "prop-types": "^15.6.0",
    "react": "^16.3.1",
    "react-native": "^0.55.3",
}
`
I am unable to view picker data contents on emulator screen can you please help me ? 
 * I didn't receive any error message or crash report while testing the example
* I changed the import path of Proptypes module from 'react' to "prop-types" in 'react-native-picker' module's index.js file and 'react-native-picker-android'`s. I didn't make any other changes.

![picker_data](https://user-images.githubusercontent.com/10031984/40234390-5bd8445c-5aaf-11e8-893d-5e4a095ad0f9.png)

**Comment by Apak00** [comment]
I have the exact same issue, could someone figure this one out?

**Comment by ninjarails** [comment]
It doesn't show on iOS on second open for me. At first open it looks fine.
