### ISSUE TITLE
How to change the selected Item style in Android?

### ISSUE THREAD

**Issue by herbertdai** [beefe/react-native-picker#32]
This module works great on iOS, but the selected item text size is too big in Android, how to change the font size? Thanks!

**Comment by xwenliang** [comment]
抱歉目前还不支持设置picker中的字体，如果想设置安卓下显示的字体需要去修改这个库所依赖的安卓版本的picker：https://github.com/beefe/react-native-picker-android

**Comment by xwenliang** [comment]
最新的原生版的picker已经发布，安卓样式有所改进，可以试下
