### ISSUE TITLE
picker 和 Modal 在android上不能一起使用。请问如何解决？

### ISSUE THREAD

**Issue by yizhi108** [beefe/react-native-picker#348]

**Comment by lehug** [comment]
+1

**Comment by wangchongwei** [comment]
> 
> 
> _No description provided._

其实是可以的，不过你要确保modal已经显示了，在让picker 显示，这个时候modal就在下面、picker在上面了。

**Comment by wangchongwei** [comment]
> 
> 
> +1，本质目的是希望picker show后，有遮挡，下面的视图不可点击

其实是可以的，不过你要确保modal已经显示了，在让picker 显示，这个时候modal就在下面、picker在上面了。

**Comment by yizhi108** [comment]
哇，真的可以。谢谢了。

**Comment by yizhi108** [comment]
需要在modal 的onshow 方法中之行picker.show的代码就可以了。
