### ISSUE TITLE
Element type is invalid Error

### ISSUE THREAD

**Issue by nosensezzz** [beefe/react-native-picker#38]
Hi, When I trying to use this component, it keeps showing a error, feel like it's some props have incorrect value.

element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `xxxx`.

do you know why?

**Comment by nosensezzz** [comment]
ps: I just use your demo code, nothing changed.

**Comment by xwenliang** [comment]
Newest version `v3.0.1` has supported to RN 0.26, update to check if there are still problems  😄
