### ISSUE TITLE
unable to resolve module ReactDefaultPerf

### ISSUE THREAD

**Issue by shaikhussian** [beefe/react-native-picker#41]
while i install this repo example pickerTest i got an error like this

![simulator screen shot 23-may-2016 6 59 51 pm](https://cloud.githubusercontent.com/assets/11956308/15472473/f1eafb6a-2118-11e6-84dd-ccd4e1f175c8.png)

**Comment by shaikhussian** [comment]
Please respond

**Comment by xwenliang** [comment]
I am so sorry but i dont kown if it was due to NPM 3.xx  [here](https://github.com/jhabdas/react-native-webpack-starter-kit/issues/7)
When i try:
```bash
react-native init NewPickerTest
cd NewPickerTest
npm install react-native-picker --save
cp $yourDir/react-native-picker/example/PickerTest/index* .
```
and then run the project, everything sames to be ok...
but when i send my code to NPM, then the problem reproduced..

**Comment by shaikhussian** [comment]
@xwenliang Thank You for your respose is there any possibility to change the color of selcted value and height and backgroungcolor

**Comment by shaikhussian** [comment]
Please respond

**Comment by xwenliang** [comment]
sorry, there is no this feature..

**Comment by g6ling** [comment]
I solved this.
In your package.json 
edit
"react": "^15.0.2",
"react-native": "^0.26.2"

If between your react-native and your react version are not fit, this problem happen.
check your react, react-native version

**Comment by xwenliang** [comment]
Make sure it's `15.0.2` and not `^15.0.2` 解决了这个问题
https://github.com/facebook/react-native/issues/7719
