### ISSUE TITLE
in iphone 5s picker cancel 'l' is not diplsying

### ISSUE THREAD

**Issue by shaikhussian** [beefe/react-native-picker#42]
hai when i run the code in 6 the picker working fine and when i check in 5s, the Cancel button 'l' is not displaying, plaese check it and update the repo, please respond to it whether it bug or any changes did i need done

**Comment by xwenliang** [comment]
since `leftBtn:title:rightBtn  = 1:4:1`, you can set `pickerTitleStyle={flex: 3}` to make button area larger
