### ISSUE TITLE
组件为什么默认是开启的- -设置了没效

### ISSUE THREAD

**Issue by ah-kevin** [beefe/react-native-picker#45]
组件为什么默认是开启的- -设置了没效

**Comment by xwenliang** [comment]
可能你当前最外层view的高度不是整个屏幕的高度，我是这么设置这个组件初始位置的
`top: Dimensions.get('window').height`
或许加个隐藏会更好...

**Comment by ah-kevin** [comment]
@xwenliang  已经解决了 3q
