### ISSUE TITLE
item scrollTo last item's choose number?android

### ISSUE THREAD

**Issue by HanBeen** [beefe/react-native-picker#51]
我在list中添加了picker后，点击第一个item后出现picker，随意滚动到一个值的位置，然后点击第二个item出现对应的数据后，稍微一滑动就直接滚动到上次选择的值的位置了，只有安卓发送了这个问题，iOS正常

**Comment by HanBeen** [comment]
我在pickerDatas里放了一个数组，包含1~20个的数字，list的上个item toggle引出来的picker滑动到20，下一个item toggle引出picker后轻轻一点就滑动到20，这是怎么回事呢？

**Comment by xwenliang** [comment]
稍等，我看下

**Comment by HanBeen** [comment]
@xwenliang hi，有没有发现问题呢？

**Comment by xwenliang** [comment]
抱歉，这么晚才回，
看了下你的代码，大致了解了
因为你的所有list是共享了同一个picker，点上一个item出来的picker，你更改了默认值，点下一个的时候，这个默认值仍然是上一个item设置的默认值，所以碰一下就就跑到这个默认值上了
建议你点其它的item的时候，将picker的默认值也一起改一下就没有这个问题了

**Comment by HanBeen** [comment]
默认值是指的selectedValue吗？我改了这个没用啊，就算它每次都是固定的从1开始，也会发生这个情况

**Comment by HanBeen** [comment]
您可以试一下我的这种在list上使用的写法吗？我在ios上没发现问题，只有在安卓上才会出现这个问题

**Comment by xwenliang** [comment]
`onPickerDone={(pickedValue) => this._changeValue(pickedValue)}`
改为
```
onPickerDone={(pickedValue) => {
    this._changeValue(pickedValue);
    this.setState({selectedValue: pickedValue})
}
```
能稍微好一些，不过还是有点bug，安卓版是自己实现的，有些bug，我看看修改下

**Comment by HanBeen** [comment]
这样写的话对于一个item来说是没问题的，但是点击其他item的时候我需要把selectedValue重新赋值成最小的那个数，所以还是不太可行，麻烦您了

**Comment by HanBeen** [comment]
现在我更新一下就可以了吗？还是改一下这个里面的代码？

**Comment by xwenliang** [comment]
你直接更新到`3.0.4`应该就可以了

**Comment by HanBeen** [comment]
我现在的就是3.0.4，再重新安装一遍就可以了吧？

**Comment by xwenliang** [comment]
刚才说错了，是`3.0.5`

**Comment by HanBeen** [comment]
噢，好的，我明天试一下，现在不在公司，很感谢您！

**Comment by HanBeen** [comment]
非常感谢！现在已经成功解决问题了。
