### ISSUE TITLE
能优化安卓的弹起速度吗？

### ISSUE THREAD

**Issue by HanBeen** [beefe/react-native-picker#52]
当我把一个1~999的数字数组给pickerData时，picker弹起的速度超级慢，至少有5秒钟之后才弹起，想问一下有优化的办法吗？

**Comment by HanBeen** [comment]
刚才的描述不太正确，是这样的，我把pickerData的数据放在了state里，初始数据弹起的速度很快，但是当我点击弹起的那个按钮时，改变state里的数据为1~999的数组，就会很慢，是我的方法有问题吗？

**Comment by HanBeen** [comment]
hi,有办法优化吗？

**Comment by xwenliang** [comment]
额，这个得有空再看了，这周内给你答复

**Comment by HanBeen** [comment]
(⊙v⊙)嗯，不过还是希望您能早一些看看，因为我这个挺急的，多谢！

**Comment by xwenliang** [comment]
刚试了下，是生成这1000个节点比较耗时，直接放到state里，app初始化的时候就生成了这1000个节点，所以点击的时候会马上响应，改变state同时弹起picker，弹起之前要先生成这些节点，所以比较耗时，目前还没有比较好的解决办法，可以试试这个安卓的native组件：[react-native-wheel](https://github.com/shexiaoheng/react-native-wheel)

**Comment by HanBeen** [comment]
谢谢，安卓的自己写吧还是
