### ISSUE TITLE
当我有多个picker的时候，速度会很慢，该怎么弄？ When I have a number of picker, the speed will be very slow, how to get?

### ISSUE THREAD

**Issue by andylidong** [beefe/react-native-picker#53]
当我有多个picker的时候，速度会很慢，该怎么弄？
When I have a number of picker, the speed will be very slow, how to get?

**Comment by xwenliang** [comment]
描述一下场景？

**Comment by andylidong** [comment]
就是我在一个界面中，有多个需要弹出选项，我把弹出的内容放在picker中，像是选择日期、选择时间、选择地址和选择原因等，界面初始化就会很卡

**Comment by xwenliang** [comment]
恩，东西多了，需要映射到原生的节点也会很多，是这个过程卡吧，打个release包试试可能会好些，目前还没有解决方法。后续可能会推出原生版的picker来提高性能

**Comment by andylidong** [comment]
好的
