### ISSUE TITLE
How to show selected value in picker

### ISSUE THREAD

**Issue by vykumar** [beefe/react-native-picker#55]
I added three wheel parallel picker in my code that is mentioned below:
```javascript
createParallelPickerData(){
      let yearData = []
      let firstRow = []
      let secondRow = []
      let thirdRow = []
      for(let i=1950;i<2050;i++){
          firstRow.push(i)
      }
      for(let j=0;j<1;j++){
          secondRow.push("to")
      }
      for(let k=1950;k<2050;k++){
          thirdRow.push(k)
      }

      yearData.push(firstRow)
      yearData.push(secondRow)
      yearData.push(thirdRow)

      return yearData
}


<Picker
    ref={(picker) => {this.picker = picker}}
    style={[styles.pickerView]}
    showMask={true}
    showDuration={300}
    pickerData={this.createParallelPickerData()}
    pickerBtnText = 'Apply'
    pickerBtnStyle = {[styles.applyBtn]}
    pickerToolBarStyle = {[styles.toolBar]}
    selectedValue={['2000', 'to', '2016']}
    onPickerDone={(pickedValue) => {
    this.setYearData(pickedValue)
}}/>
```
As you can see in above code, I added selectedValue={['2000', 'to', '2016']} to show the initially selected value of picker like '2000' in first wheel , 'to' in second wheel and '2016' in third wheel but it's not showing like that. it is showing like ['1950', 'to' , '1950'] default picker value because 1950 is the first index value of pickerData array which you can see in createParallelPickerData().

Now , I want to know how we can show the predefined selected value in picker because the value set in selectedValue property is not displaying in picker as selected value.

**Comment by xwenliang** [comment]
I think it's due to the type of `selectedValue`, try to change `['2000', 'to', '2016']` to `[2000, 'to', 2016]`.
