### ISSUE TITLE
不确定个数的数据怎么生成对应的picker?

### ISSUE THREAD

**Issue by kearons** [beefe/react-native-picker#58]
如题，我有一组数据，我不能确定需要多少个picker组件，在onpress时传入相应的index来确定pickdata,这样也不用放很多组件了，不成熟的想法，望指点啊

**Comment by xwenliang** [comment]
可以这么做，但要注意：
如果每组数据里面的数据相互独立的话，直接按照parallel模式的格式传入数据就行了，如果是相互关联的话(像地区的三级联动)最多只能支持三级

**Comment by kearons** [comment]
这么快回复啦，太感动了，这个我刚刚已经写好了，但是遇到了之前一位仁兄的问题，那就是渲染实在太慢了，等了大概一分钟把，我还以为死机了 ：（

**Comment by xwenliang** [comment]
恩，react节点太多的话，虚拟dom和真实dom间的转换确实非常耗时，估计这很难解决，除非全部原生实现，react只传入数据了

**Comment by xwenliang** [comment]
原生版的picker发布了，解决了渲染慢的问题，可以尝试下😬
