### ISSUE TITLE
iOS 端 Import进去之后出现问题!

### ISSUE THREAD

**Issue by uncleRX** [beefe/react-native-picker#61]
![simulator screen shot 2016 9 9 09 35 39](https://cloud.githubusercontent.com/assets/16251490/18372698/26da24c4-7671-11e6-8662-603ac788188d.png)
 [
react-native -0.31

**Comment by uncleRX** [comment]
尝试了 修改 提示中的 import ......

**Comment by xwenliang** [comment]
问题解决了吗
