### ISSUE TITLE
_reactNativePicker2.default.init is not a function

### ISSUE THREAD

**Issue by leo7r** [beefe/react-native-picker#62]
![screen shot 2016-09-20 at 3 35 18 pm](https://cloud.githubusercontent.com/assets/6210797/18685895/f26c164a-7f47-11e6-907b-1339a0cd06c0.png)

I try uninstall module and reinstall it but same error. What I have to do to make it work? I'm using README's example code.

Here is the result of `react-native link`:
![screen shot 2016-09-20 at 3 38 23 pm](https://cloud.githubusercontent.com/assets/6210797/18686018/5ea790d2-7f48-11e6-9bdb-a46985a93f9d.png)

**Comment by MDrooker** [comment]
Having the same issue.  Any ideas for a workaround?

**Comment by gcusnieux** [comment]
Use this documentation https://github.com/beefe/react-native-picker/tree/v3.0.5

**Comment by xwenliang** [comment]
New version `v4.0.1` published.
