### ISSUE TITLE
android 将示例代码复制进去,重新start,点击DatePicker报错,

### ISSUE THREAD

**Issue by mynane** [beefe/react-native-picker#63]
"undefined is not an object (evaluating 'Picker_init')"

**Comment by xwenliang** [comment]
去看[这里](https://github.com/beefe/react-native-picker/blob/master/example/PickerTest/index.js)的代码吧

**Comment by mynane** [comment]
重新 生成run-android apk包就解决了

单纯的npm install 和npm link 再restart ,是会报错的

**Comment by xwenliang** [comment]
报错日志发一下

**Comment by shexiaoheng** [comment]
reload只能重新加载`js`端的代码，`$ npm install`和`$ lilnk`之后相当于修改了Android端的代码，所以必须重新编辑生成新的apk包才可以。
