### ISSUE TITLE
android Picker首次弹出时,连续点击周围会报OnValueChange的错误

### ISSUE THREAD

**Issue by aijason** [beefe/react-native-picker#64]
android Picker首次弹出时,连续点击周围会报OnValueChange的错误..闪退

**Comment by xwenliang** [comment]
看下当前是什么版本

**Comment by aijason** [comment]
"react-native": "^0.25.1"

**Comment by aijason** [comment]
跟版本有关系吗

**Comment by xwenliang** [comment]
我是说picker的版本...

**Comment by aijason** [comment]
这个在哪里看版本

**Comment by aijason** [comment]
"react-native-picker": "^3.0.5",

**Comment by aijason** [comment]
我用的是"react-native-picker": "^3.0.5",这个版本的picker

**Comment by xwenliang** [comment]
这个版本是用js写的view，性能稳定性都比较差，可以试试最新的原生picker，目前最新版本`v4.0.2`
