### ISSUE TITLE
NativeModules.BEEPickerManager undefined.

### ISSUE THREAD

**Issue by walkerrandolphsmith** [beefe/react-native-picker#65]
Cannot read property '_init' of undefined. Any idea why `let Picker = NativeModules.BEEPickerManager;` would be undefined?

**Comment by xwenliang** [comment]
What is your version of Nodejs and picker?

**Comment by philohelp** [comment]
Same problem here, I cant run any of the examples. I get "Cannot read property '_init' of undefined" or cannot read property 'isPickerShow' of undefined. There must be a problem somewhere.

**Comment by shexiaoheng** [comment]
@walkerrandolphsmith  @philohelp  you execute the `react-native link` command ?

**Comment by shexiaoheng** [comment]
in you workspace
```shell
$ git clone https://github.com/beefe/react-native-picker.git
```

```shell
$ cd react-native-picker/example/PickerTest/
```

```shell
$ npm i
```

```shell
$ react-native link
```


```shell
$ react-native run-android
```

it' ok .

**Comment by walkerrandolphsmith** [comment]
Sorry for the delay. I will have to gather the information asked for. I am certain I ran `react-native link`. Given I was unable to get it to work I created my own picker and didn't make a commit that used react-native-picker. With a lack of history I may be unable to give exact version number.

**Comment by walkerrandolphsmith** [comment]
May also be good to note I used `react-native run-ios`

**Comment by xwenliang** [comment]
#67

**Comment by elado** [comment]
Same issue here. iOS. Ran `react-native link` and `yarn run ios`. `NativeModules.BEEPickerManager` is undefined.

**Comment by bithavoc** [comment]
+1

**Comment by geminiyellow** [comment]
i dont know why this issue has been closed, but got the same error.

**Comment by elado** [comment]
In my case, I  was creating the app with create-react-native-app, and I needed to yarn eject it.
