### ISSUE TITLE
「iOS」RN与原生混合开发，从原生环境切到RN后，点击弹出的Picker却在Native环境打开？！

### ISSUE THREAD

**Issue by zhangwebb** [beefe/react-native-picker#66]
场景：
做了个地域选择级联，然后比如用户编辑放到RN环境，当从原生切到RN后，点击地域选择，结果发现Picker打开在切换前的原生界面里，在RN后面。……是初始化的时间点不对么？

简单说来就是直接在RN环境调用Picker显示ok；从原生切到RN后再调用，Picker却打开在了原生环境下。（"react-native-picker": "^4.0.2"）

不确定原因，看看有人碰到类似情况没有。

这里有个参考：
https://segmentfault.com/a/1190000005761357

我再试试那个「For pure javascript version -> v3.0.5」

--------------------

更新：

1. 最后，还是「For pure javascript version -> v3.0.5」好使；
2. "react-native-picker": "^4.0.2" 用作地域级联选择时，如果是二级级联，第二级选择貌似有个问题，就是点选不中目标城市，总是跳回第一项，不知是否为个别问题。临时取巧解决办法是构造三级级联数据结构，让中间那级唯一显示固定地区或空白

**Comment by pampang** [comment]
@zhangwebb 哥们问题解决了吗，我在3.0.5上也是做地域级联，发现无法选中。我的RN版本是0.29.2，之前0.25.1是没有问题的。

**Comment by zhangwebb** [comment]
1、"react-native-picker": "^4.0.2" 新版的没解决；
2、现在使用的是「For pure javascript version -> v3.0.5」，RN版本是最新的0.34，没发现无法选中问题

**Comment by shexiaoheng** [comment]
如果当前picker是显示状态，不要做Reload和Debug之类的操作，一定要先让picker隐藏，然后再做Reload或者Debug等操作。

**Comment by shexiaoheng** [comment]
二级级联没有发现你说的问题，我这边完全正常

**Comment by pampang** [comment]
@shexiaoheng @zhangwebb 问题修复了，是我代码的问题，感谢两位~

**Comment by camellieeee** [comment]
@pampang 我也出现了二级级联总是跳到第一项的问题，你是怎么解决的呀？

**Comment by shexiaoheng** [comment]
@camellieeee 检查下你的代码，https://github.com/beefe/react-native-picker/issues/69

**Comment by camellieeee** [comment]
@shexiaoheng 我用的4.0.3版本，这个问题只会出现在地区选择上，在日期选择上没有问题，这两个都是三级的，地区选择中第二列无论初始化为什么，都会跳转到第一条数据，代码检查过了没有问题。这bug实在太奇怪了。

**Comment by pampang** [comment]
@camellieeee 我目前在用的3.0.5，没有上述的问题。似乎提主的问题跟你的近似

**Comment by shexiaoheng** [comment]
@camellieeee 代码贴下

**Comment by camellieeee** [comment]
@shexiaoheng 关键代码就这些，数据结构我看了也没问题
![10122](https://cloud.githubusercontent.com/assets/18331008/19296720/7d203832-9070-11e6-87b3-b108a916a577.png)
![1012](https://cloud.githubusercontent.com/assets/18331008/19296724/7ee7b5b4-9070-11e6-98db-0af15e55cebd.png)
![img_0596](https://cloud.githubusercontent.com/assets/18331008/19296729/88189932-9070-11e6-8031-00178b30f1eb.PNG)

**Comment by shexiaoheng** [comment]
@camellieeee 上代码。。。。    不是上图片。。。。    我要copy

**Comment by shexiaoheng** [comment]
@camellieeee 看你这个是iOS端，Android端正常吗？

**Comment by camellieeee** [comment]
现在只做了ios端

**Comment by shexiaoheng** [comment]
能否试下Android端？

**Comment by xwenliang** [comment]
@camellieeee 运行下[example](https://github.com/beefe/react-native-picker/tree/master/example/PickerTest)里面的代码，试试会不会这样

**Comment by camellieeee** [comment]
@xwenliang 也是这样的，跟我一模一样

**Comment by shexiaoheng** [comment]
@camellieeee 你该不会既设置了第一列的选中又设置了第二列的选中，并且第二列不属于第一列的子集吧？

**Comment by camellieeee** [comment]
@shexiaoheng 不会啦，代码都放图片上了，而且example跑起来也是同样的问题

**Comment by shexiaoheng** [comment]
@camellieeee 嗯  测试了下   iOS有这个bug  Android没问题，iOS已经在修复了     稍后会更新版本

**Comment by camellieeee** [comment]
刚刚还发现两个问题，1.如果这个picker实在一个modal页面里面，它会显示在modal层下面，我只能用其他的方法来代替在modal页面上的picker
2.在picker显示着的时候退出页面，picker不会马上收缩关闭，我现在只能在页面卸载的时候hide这个picker

**Comment by shexiaoheng** [comment]
@camellieeee 
1. 建议不要在modal里面使用picker...    
2. Android上你可以拦截返回键处理，先hide picker，然后再退出程序,iOS上没办法
3. 那个应该是iOS设置的默认边距,不影响的吧...

**Comment by xwenliang** [comment]
新版本`v4.0.4`发布了

**Comment by susan-github** [comment]
@camellieeee 如果这个picker是在一个modal页面里面，它会显示在modal层下面这个问题，你最后用什么方式解决的？

**Comment by susan-github** [comment]
找到了一个不错的解决方法，可以使用Modal。
datepicker.show() 在Modal的 [onShow](http://reactnative.cn/docs/0.39/modal.html#content)  方法里调用，就不会出现Modal遮挡住datepicker的情况了

**Comment by shexiaoheng** [comment]
@susan-github 新版本这个问题已经不存在了，在Modal里直接调用pick就行

**Comment by FuYiwei** [comment]
> @susan-github 新版本这个问题已经不存在了，在Modal里直接调用pick就行

ios下不会出现modal遮挡picker，安卓下出现

**Comment by FuYiwei** [comment]
> 找到了一个不错的解决方法，可以使用Modal。
> datepicker.show() 在Modal的 [onShow](http://reactnative.cn/docs/0.39/modal.html#content) 方法里调用，就不会出现Modal遮挡住datepicker的情况了

在modal onshow 执行picker.show() 在安卓下 依旧会遮挡，你是怎么处理的？
