### ISSUE TITLE
onPickerConfirm only returns changed column

### ISSUE THREAD

**Issue by JonasWho** [beefe/react-native-picker#68]
I am using the Picker with 8 colums, to create an odometer reader for a car. I have a 6 figure amount with 1 decimal. 

My problem is that if I just change 1 column, the `onPickerConfirm` method returns just that one column that I changed. Example: If I change the initial value from 012633,8 to 012632,8 then the data that  `onPickerConfirm` gives me, is ['0','0','0','0','0','2',',','0']

My exaple code is here: 
```
const pickerData = [
  [0,1,2,3,4,5,6,7,8,9],
  [0,1,2,3,4,5,6,7,8,9],
  [0,1,2,3,4,5,6,7,8,9],
  [0,1,2,3,4,5,6,7,8,9],
  [0,1,2,3,4,5,6,7,8,9],
  [0,1,2,3,4,5,6,7,8,9],
  [','],
  [0,1,2,3,4,5,6,7,8,9]
];
const selectedValue = [0,1,2,6,3,3,',',8];

Picker.init({
      pickerData: pickerData,
      selectedValue: selectedValue,
      pickerConfirmBtnText: 'OK,
      pickerCancelBtnText: 'Cancel',
      pickerTitleText: 'Choose',
      onPickerConfirm: data => {
        console.log(data)
      },
      onPickerCancel: data => {},
      onPickerSelect: data => {}
});
```

**Comment by xwenliang** [comment]
`v4.0.3` fixed this bug, thanks!

**Comment by JonasWho** [comment]
Perfect, thank YOU :)
