### ISSUE TITLE
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?

### ISSUE THREAD

**Issue by make38324** [beefe/react-native-picker#71]
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
Android在缩小再进来会报这个错

**Comment by shexiaoheng** [comment]
在程序中按Home返回桌面，键然后再从桌面进入程序？

**Comment by make38324** [comment]
是的，在程序中按Home返回桌面，键然后再从桌面进入程序

**Comment by shexiaoheng** [comment]
我这边进行此操作没有问题，你那边是每次都会发生吗？

**Comment by shexiaoheng** [comment]
@make38324 现在是什么情况了？

**Comment by make38324** [comment]
真机没有问题，模拟器有问题

**Comment by make38324** [comment]
上次还有这个问题，现在好像没问题了

**Comment by make38324** [comment]
偶然性的有时会出现，有时不会出现

**Comment by shexiaoheng** [comment]
只有模拟器会发生是吗？

**Comment by make38324** [comment]
真机有时也会出现

**Comment by shexiaoheng** [comment]
我这边模拟了很多遍也模拟不出来，你换个手机试下吧，可能跟手机有关。

**Comment by make38324** [comment]
好的，谢谢

**Comment by 277850318** [comment]
![image](https://cloud.githubusercontent.com/assets/8946022/20647891/837ff794-b4d3-11e6-80b3-deef075d49c0.png)
模拟器 真机一样  每次都出现

**Comment by shexiaoheng** [comment]
最新版本这个问题应该不会再发生了，我测试了无数遍都没有复现。
