### ISSUE TITLE
如何在点击返回按钮时,收回弹出的picker窗

### ISSUE THREAD

**Issue by aijason** [beefe/react-native-picker#72]
如何在点击返回按钮时,收回弹出的picker窗.

**Comment by aijason** [comment]
android端

**Comment by shexiaoheng** [comment]
拦截返回按钮事件查看react-native官方文档：[BackAndroid](http://facebook.github.io/react-native/docs/backandroid.html), 在该拦截中调用本组件的`hide`方法
