### ISSUE TITLE
请问是否支持列数的动态变换（根据不同的选择项变换列数）

### ISSUE THREAD

**Issue by michaelguo1991** [beefe/react-native-picker#73]
比如如下的需求：
选择“立即使用”的时候，组件变成1列；  选择其他时间（如10月14日 今天）的时候，组件变成3列
![image](https://cloud.githubusercontent.com/assets/2106440/19382508/1c9bfd92-9233-11e6-8f65-af1e34d6dbb0.png)    
![image](https://cloud.githubusercontent.com/assets/2106440/19380506/216f917a-922a-11e6-90b1-3bd01317bc33.png)

**Comment by shexiaoheng** [comment]
目前不支持，如果你可以的完善的话，可以提下PR

**Comment by michaelguo1991** [comment]
了解了，感谢
