### ISSUE TITLE
在ios中如果label超过5个汉字，会自动被截断

### ISSUE THREAD

**Issue by hejiaji** [beefe/react-native-picker#74]
如：“第三方资源” 会截成 “第三方……”，怎么样可以让它显示全部？

**Comment by hejiaji** [comment]
在Andriod上没问题，在ios里面就有这个issue

**Comment by shexiaoheng** [comment]
截图发下

**Comment by hejiaji** [comment]
@shexiaoheng 
![wechatimg1](https://cloud.githubusercontent.com/assets/19968961/19437456/14f32120-94a8-11e6-83f1-c4223e90fa17.jpeg)

如图所示，据推论应该是item的宽度的问题，原生picker的话，可以设置itemStyle中的width，这个有办法么？

**Comment by haibinyu** [comment]
pickerTitleText 有同样的问题，长度超过6个字符会被截断。

**Comment by dqisme** [comment]
我们找到了问题，给你们提个pr可以么

**Comment by shexiaoheng** [comment]
我们这边已经在改了，稍后会发布新版本 : )

**Comment by xwenliang** [comment]
😉谢谢各位，新版本`v4.0.5`发布了
