### ISSUE TITLE
选择项内容多出现省略号

### ISSUE THREAD

**Issue by iceshu** [beefe/react-native-picker#75]
请问怎么取消选择项内容多的时候出现省略号

**Comment by shexiaoheng** [comment]
什么意思？

**Comment by shexiaoheng** [comment]
直接上图吧

**Comment by iceshu** [comment]
![大概类似这样](http://img.luqidong.com/7F85A9EA-94BD-40E8-802C-9B0A3D1847A0.png)
这样的 有省略号 有什么办法可以去除么

**Comment by hejiaji** [comment]
@iceshu 上一个commit已经fix了吧 [link](https://github.com/beefe/react-native-picker/issues/74)

**Comment by iceshu** [comment]
@hejiaji  我更新了发现还是有省略号 咋回事要不要设置啥啊

**Comment by shexiaoheng** [comment]
是iOS端吧？你把node_modules下的目录删了后重新运行`npm install` `react-native link` `react-native run-ios`命令

**Comment by iceshu** [comment]
@shexiaoheng @hejiaji 好了多谢2位

**Comment by xwenliang** [comment]
执行`npm update`就好了
