### ISSUE TITLE
场景切换，picker未关闭

### ISSUE THREAD

**Issue by ryanyu104** [beefe/react-native-picker#76]
问题： 场景切换用的是navigator，旧场景的picker为打开状态时候，切换到新场景，picker未及时关闭，依然是打开状态。
建议： 在picker底部加个遮罩层，点击遮罩关闭picker，可以参考 react-native-image-picker 的做法，这样就避免了这个问题。

一点愚见，望采纳

**Comment by shexiaoheng** [comment]
建议：切换场景调用 `hide` 方法

**Comment by ryanyu104** [comment]
@shexiaoheng  调用当然可以，但是如果每个使用到picker的场景切换都调用hide的话，会有些繁琐。
