### ISSUE TITLE
您好，初始化两个picker。如果选第一个（性别选男）会返回  男，北京，东城区。

### ISSUE THREAD

**Issue by sourcespro** [beefe/react-native-picker#79]
您好，初始化两个picker。如果选第一个（性别选男）会返回  男，北京，东城区。麻烦帮忙看一下。
![image](https://cloud.githubusercontent.com/assets/7599120/19508760/8a559f04-960d-11e6-983e-06d41354a896.png)

**Comment by shexiaoheng** [comment]
错误的地方给你圈出来了，请不要在回调里面去设置组件的值。[snip20161019_6](https://cloud.githubusercontent.com/assets/3015681/19510250/ee335e7e-9614-11e6-869a-41b030e6932f.png)

**Comment by shexiaoheng** [comment]
抱歉，之前没有仔细看，正在排查问题，请耐心等待。
