### ISSUE TITLE
support BackAndroid and mask layer

### ISSUE THREAD

**Issue by tza17313** [beefe/react-native-picker#80]
### Version
- react-native-picker v4.0.7
- react-native v0.35.0
### Platform
- Android
### Expected behaviour

support BackAndroid and mask layer
### Actual behaviour

does not support BackAndroid and mask layer
### 详细说明
- 在andriod中，如果按返回键，并不会把Picker 隐藏掉；
- 在一个表单中，如果有TextInput，输入时弹出了键盘；这时调用 `Picker.show()` ，并不会把键盘隐藏掉；
- 或者先调用了`Picker.show()` ，再去点击TextInput，弹出键盘，这时键盘被挡住了；是否可以增加一个遮罩层来解决这个问题？

**Comment by PeterRock** [comment]
纯JS版本时，有个遮罩不知道为什么后来取消了

**Comment by xwenliang** [comment]
1. 建议监听`hardwareBackPress `事件，手动处理，这样可以灵活控制是返回上级还是隐藏picker
2. 建议调用`Picker.show()`之前先调用`dismissKeyboard`
3. 后续会考虑支持，这个遮罩可以自己二次封装实现，点击遮罩的时候调用`Picker.hide()`

**Comment by xwenliang** [comment]
@PeterRock 纯JS版本的现在还有的 [v3.0.5](https://github.com/beefe/react-native-picker/tree/pure-javascript-version)
