### ISSUE TITLE
Is it possible to show picker in a model (dialog)?

### ISSUE THREAD

**Issue by haydenluo** [beefe/react-native-picker#81]
I'd like to after I call picker.show(), no other parts of parent view could be clicked(or touched).

**Comment by xwenliang** [comment]
means you want a mask?

**Comment by haydenluo** [comment]
Yes.  Is it possible to add an extra parameter(may be 'modelMode') in picker.Init() method, to enable such behavior?
This is a new requirement, not issue, but I can't find where to submit new requirement, so post it here.

**Comment by vivaxy** [comment]
@haydenluo Did you managed to do it? I tried to use Modal along side with Picker, but the picker is covered by Modal. https://github.com/beefe/react-native-picker/issues/148

**Comment by mykelaballe** [comment]
also having this issue on iOS. its fine on Android

**Comment by KingDr** [comment]
It's very simple.
try this:
```
<Container>
<Content>
<YourViewComponent />
</Content>
{this._renderBgmask()}
</Container>
```

while the function is
```
if (this.state.showbg) {
            return (
                <View style={{position:'absolute', top: 0, bottom: -1000, left:0, right: 0, backgroundColor:'rgba(20,20,20, 0.3)'}}>
                </View>
            )
        } else {
            return null;
        }
```
