### ISSUE TITLE
Picker.show() android上没有反应

### ISSUE THREAD

**Issue by jacobzeng** [beefe/react-native-picker#84]
"react": "15.3.2",
"react-native": "0.33.0",
"react-native-picker": "^4.0.8",

android 4.4.1

调用Picker.show()没有反应，没看到UI，也没有任何错误，没试ios平台

**Comment by jacobzeng** [comment]
怪事，中间做其他功能的时候，突然弹出来了，后来刷新又不出来了。。

**Comment by shexiaoheng** [comment]
调用`init`方法即可，只有在调用`hide`方法后才会调用`show`方法
