### ISSUE TITLE
android正常，ios 9.3正常，ios 8.1 有白边,怎么修正？

### ISSUE THREAD

**Issue by 277850318** [beefe/react-native-picker#85]
![image](https://cloud.githubusercontent.com/assets/8946022/19959434/c3e8aaec-a1e1-11e6-9514-e8582ff5bb8d.png)
![image](https://cloud.githubusercontent.com/assets/8946022/19959877/86c30ccc-a1e4-11e6-94f5-9da537191098.png)
![image](https://cloud.githubusercontent.com/assets/8946022/19959895/a0cb3c70-a1e4-11e6-9e80-fb82335d1f92.png)

**Comment by shexiaoheng** [comment]
你改iOS的代码了吗？

**Comment by 277850318** [comment]
没

**Comment by shexiaoheng** [comment]
这边测试正常啊。。    贴下你的代码吧

**Comment by shexiaoheng** [comment]
这边测试正常显示，贴下你的代码吧

**Comment by shexiaoheng** [comment]
你用的是真机还是模拟器？

**Comment by 277850318** [comment]
就是跑的他自己的example

**Comment by xwenliang** [comment]
经查明是iOS<9.0的版本中`picker view`的高度只能是162,180,或216，并不支持自定义
`v4.0.9`已修复此问题，感谢
