### ISSUE TITLE
will not render for React Native 37

### ISSUE THREAD

**Issue by skyride99** [beefe/react-native-picker#92]
It just blows up in render.

**Comment by ssomnoremac** [comment]
Which version of the picker? 3 or 4? 3 isn't showing up for me.

**Comment by skyride99** [comment]
Android, version 4+ of the picker.
Also version 3 does not show up, there is nothing inside the picker.

**Comment by ssomnoremac** [comment]
So there is a breaking change to RN36 that has to do with changing `flex` to `flexGrow`, you can get it to [look like this other issue](https://github.com/beefe/react-native-picker-android/issues/13) by changing this on the picker container. I'm going to look at v4 to see if it's the same.

**Comment by skyride99** [comment]
I went back to RN 0.32 and 4.10 of the picker

I have something like this:

<Picker
              ref={'refCategory'}
              style={{height: 300, backgroundColor: '#fff'}}
              pickerHeight={300}
              showDuration={300}
              pickerData={['Resort', 'Dive Shop', 'Vehicle' ]}
              pickerCancelBtnText={''}
              pickerBtnStyle={{color: '#439FDF'}}
              selectedValue={this.state.selectedOption}
              onValueChange={(value) => this.changeCategory(value)}
            />
And that will not render.... is there something different in the API for 4?

**Comment by shexiaoheng** [comment]
Use like [this](https://github.com/beefe/react-native-picker#step-3---import-and-use-in-project)
```javascript
 import Picker from 'react-native-picker';

    let data = [];
    for(var i=0;i<100;i++){
        data.push(i);
    }

    Picker.init({
        pickerData: data,
        selectedValue: [59],
        onPickerConfirm: data => {
            console.log(data);
        },
        onPickerCancel: data => {
            console.log(data);
        },
        onPickerSelect: data => {
            console.log(data);
        }
    });
    Picker.show();
```

**Comment by ssomnoremac** [comment]
I'm pretty sure you're not on 4.10, it's a completely different implementation just like mentioned above

**Comment by skyride99** [comment]
ok i got 4.10 working. But how do you have multiple pickers?

 import Picker1 from 'react-native-picker';
 import Picker2 from 'react-native-picker';

Picker1.init({});
Picker2.init({});

Picker1.show();
Picker2.show();

Is that right?

**Comment by shexiaoheng** [comment]
Read [README.md](https://github.com/beefe/react-native-picker#support-two-modes)
