### ISSUE TITLE
not enough pickers for date/hour/min/am-pm

### ISSUE THREAD

**Issue by ssomnoremac** [beefe/react-native-picker#95]
v4
The native performance is great but I'm struggling to implement the simplest of date/time pickers. Before, I forked v3 to use it as two static pickers: one for date and one for time. Now I can't really do that so I need four in the same picker. Or else, I need to do this on two screens, which I'd prefer not to do and military time is not an option in the US. Suggestions?

**Comment by xwenliang** [comment]
Sorry to be so late, now it was easy to implement by the new feature `Picker.select`,
take a look at the`TimePicker` of [this example](https://github.com/beefe/react-native-picker/tree/master/example/PickerTest)
