### ISSUE TITLE
Run failed on Android device

### ISSUE THREAD

**Issue by susan-github** [beefe/react-native-picker#97]
**RN Version:** 0.38.0
**Picker Version:** 4.0.10
**Error:** 
undefined is not an object(evaluating 'Picker._init')  
init index.js: 35

**Comment by fozzarelo** [comment]
Same here man.. im running in on ios..

**Comment by susan-github** [comment]
Xcode Project-》clean.   Run “react-native link”. it will tell you if you link success. After link， you need to reinstall it.
