### ISSUE TITLE
Picker.init is not a function??

### ISSUE THREAD

**Issue by fozzarelo** [beefe/react-native-picker#98]
Right of the example.. running on ios, rn0.3.x im i missing something?

**Comment by obibring** [comment]
@shexiaoheng any ideas? The library is broken for me with the following error:
<img width="320" alt="screen shot 2016-12-04 at 5 26 19 pm" src="https://cloud.githubusercontent.com/assets/1755331/20869724/d07c3332-ba46-11e6-815a-dc9fbf9209b7.png">

Here's my code:
```js
import React from 'react';
import { TouchableWithoutFeedback, Text } from 'react-native';
import Picker from 'react-native-picker';

export default class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    Picker.init({
      pickerData: [0, 5, 10, 15]
    })
  }
  render() {
    return (
      <TouchableWithoutFeedback onPress={() => Picker.show()}>
        <Text>Click Me To Show Picker</Text>
      </TouchableWithoutFeedback>
    )
  }
}

**Comment by movetosun** [comment]
me too.
OS: android
rn:  0.30
picker: 4.0.10

**Comment by shexiaoheng** [comment]
@obibring are you run `react-native link`?

**Comment by obibring** [comment]
I'm using [exponent](http://www.getexponent.com).

**Comment by shexiaoheng** [comment]
@obibring I'm download the `Exponent XDE`, but when i create project , the always displayed 'Downloading project files..'

**Comment by MattyK14** [comment]
Encountering this issue after running `react-native link`. 

Both Android & iOS.
RN: 0.39.0
Picker: 4.0.10

**Comment by shexiaoheng** [comment]
### Android platform
after run `react-native link react-native-picker` and check the following files:
* android/settings.gradle
```gradle
include ':react-native-picker'
project(':react-native-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-picker/android')
```
* android/app/build.gradle
```gradle
compile project(':react-native-picker')
```
* android/src/main/java/com.xx/MainApplication.java
```java
import com.beefe.picker.PickerViewPackage;

private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                new MainReactPackage(),
                new PickerViewPackage()          // Added there
            );
        }
    };
```

**Comment by fozzarelo** [comment]
guys.. im going to bail on this one.. good luck.

**Comment by MattyK14** [comment]
@shexiaoheng the files mentioned are correct.

**Comment by duydatpham** [comment]
me too,
How can i fix it, pls ?

**Comment by shexiaoheng** [comment]
@MattyK14 

```shell
$ react-native init PickerTest
```

```shell
$ cd PickerTest
```

```shell
$ npm i react-native-picker --save
```

```shell
react-native link react-native-picker
```

```javascript
 import Picker from 'react-native-picker';

let data = [];
for(var i=0;i<100;i++){
        data.push(i);
}

Picker.init({
        pickerData: data,
        selectedValue: [59],
        onPickerConfirm: data => {
                console.log(data);
        },
        onPickerCancel: data => {
                console.log(data);
        },
        onPickerSelect: data => {
                console.log(data);
        }
    });

Picker.show();
```

```shell
$ react-native run-android
```

react-native : v0.39.2
react-native-picker : v4.0.10

It's ok , no problem .

**Comment by shexiaoheng** [comment]
@obibring I tried your code, showing normal . In addition, Picker.init() will automatically show(), do not need to call the show(), the best way is when you call hide() later call show()

**Comment by shexiaoheng** [comment]
@duydatpham Make sure you have successfully referenced this component.

**Comment by shexiaoheng** [comment]
@all If there is "undefined is not an object (evaluating 'Picker._init')" this mistake, you must not have the correct reference to this component lead to

**Comment by duydatpham** [comment]
Thanks for supporting me, bro :) 👍

**Comment by shexiaoheng** [comment]
Can be used normally ?

**Comment by duydatpham** [comment]
yes, i tried your suggest with new project.
I'll try it with my project now :)

**Comment by duydatpham** [comment]
OMG, i tried it on IOS, i have this error. But not in android :D
I linked your project with cmd "react-native link react-native-picker"
can you tell me how can i link it on ios again, pls ?

**Comment by shexiaoheng** [comment]
💃

**Comment by duydatpham** [comment]
hi, i still have a problem. If i run my project with debug mode, i have a bug. Pls check the attached image.
![screen shot 2016-12-16 at 2 54 56 pm](https://cloud.githubusercontent.com/assets/5369097/21255681/05cafca0-c3a0-11e6-81ad-8486b202028b.png)

**Comment by shexiaoheng** [comment]
Double-check whether the reference is successful

**Comment by shexiaoheng** [comment]
```javascript
import Picker from 'react-native-picker';
console.log(Picker);
```
if Picker is undefined , there must be a problem with the reference

**Comment by pannz** [comment]
![image](https://cloud.githubusercontent.com/assets/5423451/21539219/9a13b3ae-cddf-11e6-968e-2ca024ffde93.png)

still met the problem

**Comment by pannz** [comment]
try again 
call before use Picker.init({...})
still met the error!
![image](https://cloud.githubusercontent.com/assets/5423451/21539302/8549b54e-cde0-11e6-8270-2d62f65ae288.png)

I give up for this one

**Comment by duydatpham** [comment]
@pannz : hi, are you running on IOS ?

**Comment by shexiaoheng** [comment]
#### Step 1

```shell
$ git clone https://github.com/beefe/react-native-picker.git
```

* Correct screenshot

<img width="645" alt="1" src="https://cloud.githubusercontent.com/assets/3015681/21541096/e44a5a54-cdee-11e6-9f55-d7bd72ab7574.png">


#### Step 2

```shell
$ cd react-native-picker/example/PickerTest/android
```

* Correct screenshot

<img width="566" alt="2" src="https://cloud.githubusercontent.com/assets/3015681/21541431/3749c10c-cdf1-11e6-9c4f-afb4a04f29ee.png">


#### Step 3

```shell
$ npm install
```

* Correct screenshot

<img width="641" alt="3" src="https://cloud.githubusercontent.com/assets/3015681/21541269/f4a940da-cdef-11e6-9145-12093c5fad83.png">


#### Step 4

```shell
$ react-native link react-native-picker
```
and
```shell
$ react-native run-android
```

* Correct screenshot

<img width="1212" alt="4" src="https://cloud.githubusercontent.com/assets/3015681/21541097/e44ab4ae-cdee-11e6-825b-a6e6e28bf26f.png">

**Be sure to be there:**
```shell
rnpm-install info Android module react-native-picker is already linked
rnpm-install info iOS module react-native-picker is already linked
```

### Running screenshots

![result](https://cloud.githubusercontent.com/assets/3015681/21541134/210cd016-cdef-11e6-8fc7-f5d5df441722.jpg)

**Comment by pannz** [comment]
@duydatpham yeah, iOS,  I use another solution anyway,  I will try this later to see what really going on

**Comment by duydatpham** [comment]
@pannz : You can edit your xcode project like picture. If it still don't run, i don't have any solution :(
![screen shot 2016-12-30 at 11 44 58](https://cloud.githubusercontent.com/assets/5369097/21559810/ea382ee0-ce85-11e6-9b42-efd5433a4e2e.png)

**Comment by pannz** [comment]
@duydatpham I will try later,  I'm now occupied in another process

this remind me that when intergrated to an exsit project,  run the node command `rn run-ios` will use cache build before

**Comment by esutton** [comment]
On iOS I am getting this issue "ExceptionsManager.js:63 Cannot read property '_init' of undefined"

It appears RCTBEEPickerManager an console.log dump of Picker reference is defined.

![screen shot 2017-01-03 at 2 26 05 pm](https://cloud.githubusercontent.com/assets/6115047/21621883/a27d3c7e-d1c0-11e6-8015-fe5ddc82f6ab.png)

**Comment by shexiaoheng** [comment]
@esutton this Picker is [index.js](https://github.com/beefe/react-native-picker/blob/master/index.js) , error 'Cannot read property '_init' of undefined is [this](https://github.com/beefe/react-native-picker/blob/master/ios/RCTBEEPickerManager/RCTBEEPickerManager.m#L27) , the reference may have failed

**Comment by duydatpham** [comment]
@esutton : i also had this error. But when i run my project with Release mode in ios, this error was fixed :D

**Comment by esutton** [comment]
@shexiaoheng Thank you for your help.

I understand the error indicates it cannot find the **_init** method of native module **RCT_EXPORT_METHOD**.

File:  [RCTBEEPickerManager.m](https://github.com/beefe/react-native-picker/blob/master/ios/RCTBEEPickerManager/RCTBEEPickerManager.m)  
`RCT_EXPORT_METHOD(_init:(NSDictionary *)indic){`

I do not know what the problems is.   The lib appears to be building without problems and Xcode linking looks good.

**Comment by shexiaoheng** [comment]
Clear the previous references , run 
```shell
$ react-native link react-native-picker
```
get this :

<img width="759" alt="2017-01-04 11 18 11" src="https://cloud.githubusercontent.com/assets/3015681/21630792/8ada8432-d26f-11e6-9703-1d2d8b5ed26d.png">

It is a good idea to initialize a new project and then execute the following commands

```shell
$ npm i react-native-picker --save
```

```shell
$ react-native link react-native-picker
```

**Comment by esutton** [comment]
Linking looks correct to me:

<img width="938" alt="screen shot 2017-01-04 at 7 26 33 am" src="https://cloud.githubusercontent.com/assets/6115047/21643703/75161e6a-d24f-11e6-9723-df23662bf0db.png">

**Comment by esutton** [comment]
@shexiaoheng I am good now.

1. I changed Xcode to a debug build, then cleaned, and build, and picker now works.
2. I switched Xcode back to debug build, then cleaned, and build, and picker now works.

Thank you for your help.

**Comment by shexiaoheng** [comment]
@esutton great :smile:

**Comment by buskerone** [comment]
Confirmed! Thanks @esutton ! Running the app from Xcode solves the problem.

**Comment by kcmars** [comment]
@shexiaoheng 
zhangpingdeMacBook-Air:GLYSB zhangping$ npm i react-native-picker --save
GLYSB@0.0.1 /Users/zhangping/rn/aiyun/GLYSB
└── react-native-picker@4.0.18 

zhangpingdeMacBook-Air:GLYSB zhangping$ react-native link react-native-picker
rnpm-install info Android module react-native-picker is already linked 
rnpm-install info Linking react-native-picker ios dependency 
rnpm-install info iOS module react-native-picker has been successfully linked 
zhangpingdeMacBook-Air:GLYSB zhangping$ react-native link react-native-picker
rnpm-install info Android module react-native-picker is already linked 
rnpm-install info iOS module react-native-picker is already linked 
zhangpingdeMacBook-Air:GLYSB zhangping$ 
 我已经成功安装并link，在android上运行时正确的，在iOS上运行就报错了，错误根上面的一样，找不到init() 方法

**Comment by kadzier** [comment]
Was having this exact same error on Android after installing and linking everything correctly; and it turned out I simply had to restart the project by running `react-native run-android` over again, instead of just doing a quick reload.  Now it works perfectly!

**Comment by Shubham1992** [comment]
Following the included installation instructions, I was stuck for 2 hours on "RCTBridgeModule.h not found" errors.

In the end I was able to fix these by not installing the Pod at all. Here's what I did:

yarn add react-native-picker
react-native link
open podfile and DELETE the RN picker line that was added
manually drag node_modules/react-native-picker/ios/RCTBEEPickerManager.xcodeproj to Xcode under [Project] -> Libraries (making sure it's at the same level as other libs)
Open Build Phases -> Link Binary With Libraries, and drag the .a file from this lib's .xcodeproj -> Products in Xcode there
Build and use
As stated, the instructions didn't work for me at all and linking the Pod was totally unnecessary.

Do the instructions need to be updated? It seems like yes. I'd like to avoid anyone else going through all this hair-pulling, which was insane. In the end the Pod setup just appeared to be broken, b/c it could not find its React dependencies.

RN version: 0.50.3

**Comment by ChandniSharma** [comment]
I also try all above solutions and getting same error that is 'Undefined is not an object Picker.
-init'.
Does any other picker library available which is similar to this library?
On top 'Cancel' and confirm button present.

**Comment by p76** [comment]
> #### Step 1
> ```shell
> $ git clone https://github.com/beefe/react-native-picker.git
> ```
> 
> * Correct screenshot
> 
> <img alt="1" width="645" src="https://cloud.githubusercontent.com/assets/3015681/21541096/e44a5a54-cdee-11e6-9f55-d7bd72ab7574.png">
> 
> #### Step 2
> ```shell
> $ cd react-native-picker/example/PickerTest/android
> ```
> 
> * Correct screenshot
> 
> <img alt="2" width="566" src="https://cloud.githubusercontent.com/assets/3015681/21541431/3749c10c-cdf1-11e6-9c4f-afb4a04f29ee.png">
> 
> #### Step 3
> ```shell
> $ npm install
> ```
> 
> * Correct screenshot
> 
> <img alt="3" width="641" src="https://cloud.githubusercontent.com/assets/3015681/21541269/f4a940da-cdef-11e6-9145-12093c5fad83.png">
> 
> #### Step 4
> ```shell
> $ react-native link react-native-picker
> ```
> 
> and
> 
> ```shell
> $ react-native run-android
> ```
> 
> * Correct screenshot
> 
> <img alt="4" width="1212" src="https://cloud.githubusercontent.com/assets/3015681/21541097/e44ab4ae-cdee-11e6-825b-a6e6e28bf26f.png">
> 
> **Be sure to be there:**
> 
> ```shell
> rnpm-install info Android module react-native-picker is already linked
> rnpm-install info iOS module react-native-picker is already linked
> ```
> 
> ### Running screenshots
> <img alt="5" width="411" src="https://cloud.githubusercontent.com/assets/3015681/21541695/5ef13b48-cdf3-11e6-8f8c-e10e5983df4b.png">

我按照上面的步骤来，可是还是null is not an object(evaluating 'Picker._init'),我不知道哪里出了问题
